### ISSUE TITLE
Right way to end-to-end test with events?

### ISSUE THREAD

**Issue by mrb** [arc-repos/architect#115]
I'd like to set up my test harness to be able to do the following:
- Enqueue a job
- Sandbox server picks up job, finishes it
- Query the local db to assert results of job

I'm struggling a bit with this because of the interaction of `ARC_LOCAL` and `NODE_ENV`. To get around this temporarily, I ran `npm test` without `ARC_LOCAL=1`, and placed a symlink in the random location where the test script asked me to. This seemed to work though it's currently throwing some other random errors.

Anyhoo, easy local testing is important to me and will help adoption, so I was wondering if you had any thoughts or examples there to share! 

Thanks again for everything, Arc makes programming fun for me again :)

**Comment by brianleroux** [comment]
This took far too long to address! Here's an example repo https://github.com/arc-repos/arc-example-events-pubsub update for 4.x!
