### ISSUE TITLE
add @queue support to sandbox

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#131]
already stubbed into architect/functions just need to modify some lookup paths

**Comment by grncdr** [comment]
So I took a look at the code for the sandbox event bus, and it seems like "just need to modify some lookup paths" refers to https://github.com/arc-repos/architect/blob/728ab590de97849a75a8e5ed3f783e3d1ca3fa4a/src/sandbox/events/_subprocess.js#L9

Would a PR to finish this up be welcome? I was thinking of changing the "local mode" implementations in `@architect/functions` to post to `/queues` and `/events` respectively, then pass that information to the subprocess spawned by the sandbox so it knows where to lookup the lambda function.

**Comment by brianleroux** [comment]
omg yes, would super appreciate the help!

**Comment by brianleroux** [comment]
this is dope / thx so much!
