### ISSUE TITLE
Architect 4(!)

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#157]
After a ton of community feedback we’re preparing to release Architect 4.x to tighten up the core and make onboarding to AWS Lambda functions even easier. 

## Things that are different
- One repo to rule them all: `arc-repos/architect`
- New npm package name: `npm i @architect/architect`
  - `@architect/workflows` will be marked deprecated but will NOT be destroyed, and will remain up
  - Opt into these changes whenever you're ready!
- Simplified to five Lambda function types: 
  - `@http` (API Gateway)
  - `@events` (SNS)
  - `@queues` (SQS)
  - `@scheduled` (Cloudwatch Events)
  - `@tables` (DynamoDB triggers)

## Things we added
- Generic HTTP functions (`@http`)
  - Arc users will no longer be bound by a limited set of content-type based functions, limited methods, and limited number of status codes
    - `@http` will support any status code, any HTTP method, and any content-type
  - Zero deps by default!
  - Zero config by default!
  - CORS is a boolean flag on any route
  - Arc’s anonymous signed sessions are now opt-in
  - Middleware will now be opt-in (and the old arc route style will be supported by opt-in)
- `/public`
  - Much faster, easier (and clear default!) path for getting static assets onto S3 / CF
  - `/public` will always be present in Arc projects moving forward, and be mounted locally in sandbox. However, it will be inert if you haven’t defined buckets with `@static` in your .arc manifest.
  - Improvement: when mounted locally in sandbox, public will only match filenames found in the local fs (as opposed to by filetype today); requests for non-matching files will be passed through if using the `req._static()` helper

## Things we plan to remove
- Content-Type functions: `@html`, `@css`, `@js`, `@json`, `@xml`, and `@text`
  - With the addition of generic HTTP functions, you can deliver any kind of content, not just html, css, js, json, xml and text
  - Content-Type based HTTP routes was a difficult tradeoff that we made early on in Architect that was necessary at the time because API Gateway did not have the necessary custom header support for this to be configurable
  - Content-Type based HTTP routes have created a brittle and difficult to scale maintenance problem for Architect, as these paths rely on a complex set of velocity templates
  - Arc users have consistently told us that content-type based routes didn’t make sense, and were clumsy and difficult to work with
  - Arc docs are massively duplicative because of the overlapping functionality of content types, thereby adding confusion and difficulty to ramping new Arc developers
- `.static`
  - We heard a lot of feedback from the community around Arc's static asset story; `.static` was not discoverable, difficult to learn, and not intended to be checked into source, which made it ineligible for the most common uses of static assets
  - As a result, `.static` wasn’t used very much, so we wanted to make something more in line with what folks are used to and looking for

## Next steps
- Contribute feedback!
- Big docs refactor to reflect these new features, functionality, examples, and thinking
- Upgrade to 4.x

## Timeline
- Aiming for initial release 10/22/2018

**Comment by bcbailey** [comment]
+1

**Comment by ryanblock** [comment]
For posterity, from the Architect community Slack:

**glenngillen**: The only feedback I have is these all seem sensible and worthwhile to me. :shipit: 

**jkarsrud**: Holy :poop:, that is awesome news! I *can’t wait* to actually try this out!

**Comment by ryanblock** [comment]
A quick heads up:
- 4.0 RC1 is available now at https://www.npmjs.com/package/@architect/architect
- Updated docs staged at https://stage.arc.codes/
  - Upgrade guide: https://stage.arc.codes/guides/upgrade
- Announcement coming early this week!

Closing issue for now. Thanks for your feedback, everybody – looking forward to your 4.x bug reports and feature requests! 🕵🏽‍♀️

<img src="https://media3.giphy.com/media/WuZ2Yb29Z3J72/giphy.gif">
