### ISSUE TITLE
async route handlers returning response headers, but no response body

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#162]
**Describe the bug**

There are three different arc 'Hello World' examples below. While 1 (a traditional callback handler) works, 2 and 3 fail - they return a response that has headers, but no body. 3 is currently deployed on https://0fi9ete7v3.execute-api.us-west-2.amazonaws.com/staging 
                                                             
                Node 8.12.0                                  
                 npm 6.4.0                                   
                .arc 4.0.1                                   
                                 
**To Reproduce**

    // 1. Not sure where I got this, but this works
    // Is it out of date?
    // 'arc' is unused in this code, but will fail if not included
    // let arc = require("@architect/functions")
    // function route(req, res) {
    // 	console.log(JSON.stringify(req, null, 2))
    // 	res({ html: `hello world` })
    // }
    // exports.handler = arc.html.get(route)

    // 2. From https://arc.codes/
    // Returns headers, but no body
    //
    // exports.handler = async function http(request) {
    // 	return {
    // 		type: "text/html",
    // 		body: "<h1>Hello World! 🎉</h1>"
    // 	}
    // }

    // 3. From https://arc.codes/guides/http
    // Returns headers, but no body
    //
    // exports.handler = async function http(request) {
    // 	return {
    // 		status: 201,
    // 		type: "text/html; charset=utf8",
    // 		body: `
    //     <!doctype html>
    //     <html>
    //       <body>hello world</body>
    //     </html>
    //    `
    // 	}
    // }

With 2 and 3, FireFox and Chrome DevTools show response headers, but no response bodies:

Headers:

![image](https://user-images.githubusercontent.com/172594/47363851-b818af80-d6cf-11e8-8d65-053ed4e4a7ef.png)

No bodies:

![image](https://user-images.githubusercontent.com/172594/47363867-c4047180-d6cf-11e8-86ce-8331335b7cb3.png)

**Expected behavior**

Delicious response bodies.

Note I'm deploying from Windows: `Microsoft Windows NT 10.0.17763.0`

**Comment by ryanblock** [comment]
We’ll look right into this! A quick troubleshooting question: do you have a non-Windows machine we can use to see if you have the same issue when using the same arc file and code creating resources from Mac or Linux?

We aim for full Windows support, just want to begin isolating the surface area of the problem.

**Comment by mikemaccana** [comment]
I just noticed that after updating `architect` (the hello world was made on architect 3 originally), workflows might still be outdated.

  "dependencies": {
    "@architect/architect": "^4.0.1",
    "@architect/workflows": "^3.5.11"
  }

Is `workflows` out of date? I'm going to recreate the project from scratch on arc 4 and go from there.

**Comment by mikemaccana** [comment]
Also example 3 had some filth in there (I was testing to see if the headers used in the route were being used in the browser - they're not, setting a weird content type doesn't change anything), I've removed it.

**Comment by ryanblock** [comment]
Ah, that's the problem! Workflows is now deprecated as of 4.x, we apparently still need to do that. I'd suggest using `npx inventory nuke` to blow away your project (or just use another `@app` name, either works) and remove `@architect/workflows` from your `package.json`. That should set you straight!

I feel confident that's the issue, but just for reference, I was unable to using the boilerplate code and the two examples you included as failing: https://he1jnhtrag.execute-api.us-west-2.amazonaws.com/staging
