### ISSUE TITLE
Add docs on destroying AWS resources (npx destroy etc)

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#163]
**Describe the bug**

I wish to destroy the various resources I created when I ran `npx create` and that I can see when I run `npx inventory`. 

I can't see the opposite of `npx create`. Running `ls .\node_modules\.bin` doiesn't show anything obvious, and there's nothing in the sidebar at `https://arc.codes/`. Hopefully whatever the command is has a suitable scary name and not something vague like `drop`.

**Comment by ryanblock** [comment]
Hey Mike, I mentioned in this in #162 but you'll want to use `npx inventory nuke` (and probably additionally `ARC_NUKE=tables npx inventory nuke`): https://arc.codes/reference/arc-inventory
