### ISSUE TITLE
Minor Windows fixes for 4.0 announcement

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#165]
For https://blog.begin.com/introducing-architect-4-0-faster-lighter-simpler-serverless-59f6dc156bf2 (I have no idea if Medium 'private notes' are private for me or private between for me and author)..

    mkdir testapp && cd testapp && npm init --yes

Will need to be multiline, and:

    ARC_LOCAL=1 npx create

Will become:

    $env:ARC_LOCAL= 1
     npx create

**Comment by ryanblock** [comment]
`SET ARC_LOCAL=1` would work, yeah? (That doesn't need to be un-set after that terminal session is over, yes?)

**Comment by ryanblock** [comment]
Added Windows instructions, please let me know if those don't work!

**Comment by mikemaccana** [comment]
Checked, I still see `&&` instead of a multiline and `ARC_LOCAL=1` with no 'for Windows use:'  anywhere.

**Comment by mikemaccana** [comment]
Oh wait, they're at the end.

Rather than assume nix, I'd just keep the commands the same and note where they're different. I can send a PR if you like.

**Comment by ryanblock** [comment]
Sure, happy to take a look around!

I wish Medium made it easier for us to select the system environment, but unfortunately their code blocks are super primitive.

No source on this, just post up here how you think it ought to read!

**Comment by brianleroux** [comment]
hey @mikemaccana maybe we should make this a cli problem instead of a shell problem. how do you feel about `npx create local` or `npx create --local` or `npx create -l` (or all three?)

**Comment by ryanblock** [comment]
fwiw, personally partial to `npx create --local` (with optional `-l` shortcut), but this is something we should do in no small part for Windows developers, @mikemaccana let us know!

**Comment by mikemaccana** [comment]
Depends whether you think it's more an env variable or not. I;m just getting started with Architect so it's really your decision, Otherwise I'd just:

1. Make (for both systems), the `&&` into a single line.

2. Add, at the start of 'Generate your project locally.'

     Enable the `ARC_LOCAL` environment variable. For Unix, that's:

          ARC_LOCAL=1
  
     or for WIndows:

         $env:ARC_LOCAL = 1

**Comment by ryanblock** [comment]
Personally I'm a fan of cli tools (especially those that get used in automation) having many ways to pass configuration, be it flags, corresponding env vars, manifests, etc. – right now Architect supports 2 out of 3, and flags is something we've probably waited long enough to implement.

**Comment by ryanblock** [comment]
Yeah, I'm def not proposing we deprecate reading env vars for these things, additive change only here. Profile and region are already available as `.arc` `@aws` configurations, for example.

**Comment by ryanblock** [comment]
Followup:
- https://github.com/arc-repos/architect/issues/178
- https://github.com/arc-repos/architect/pull/179
