### ISSUE TITLE
Logging documentation lacking

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#169]
Per https://arc.codes/guides/logging, console.logs should show up in Logwatch. The current docs don't mention this, but it looks like at minimum we need to create a log group, and create a log stream inside that group. Even then, logs don't show up in the stream. What else needs to happen to make logwatch  work?

![image](https://user-images.githubusercontent.com/172594/47426862-70a12a80-d786-11e8-86bb-27c36d451c05.png)

**Comment by brianleroux** [comment]
we automatically create all that stuff; you just need to call `console.log` at least once from the lambda where you want to see the logs! (just tested it still works… agree we need a better story here… `npx logs` ?

**Comment by mikemaccana** [comment]
I just checked and this was completely user error / typical AWS UX spiciness. AWS Logwatch just signed into a random region which had no logs (or any other infrastructure).

**Comment by mikemaccana** [comment]
Thanks for your patience!
