### ISSUE TITLE
sandbox 404s when using arc.json, a real deploy works fine

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#170]
`npx sandbox` returns a 404 on / on Windows, a 200 on / for a real deploy. I can send you the repo if you want, but it's just a copy of the tutorial.

                Node 8.12.0                                  
                 npm 6.4.1                                   
                .arc 4.0.4

**Comment by brianleroux** [comment]
whats the `.arc` look like? (and/or which tutorial link?) seems ok here but wanna repro!

**Comment by mikemaccana** [comment]
`arc.json` is just:

    {
      "app": "testapp",
      "http": [
        {
          "get": "/"
        }
      ]
    }
  }

Will try reverting it to the `.arc` format and see if that fixes it.

**Comment by ryanblock** [comment]
Ah, I found this one earlier this week! It’s fixed in 4.1, RC is on NPM now if you want to check it out. Release this or next week.

https://github.com/arc-repos/architect/issues/168

**Comment by mikemaccana** [comment]
Rock and roll. Thanks Ryan! 🙂
