### ISSUE TITLE
Split staging and production between two AWS accounts

### ISSUE THREAD

**Issue by sentience** [arc-repos/architect#173]
Our company deploys production applications to one AWS account, and non-production applications to a different AWS account.

What I'd like to be able to do is create and then later re-deploy to staging:

```
ARC_DEPLOY=staging aws-vault exec arc-staging -- npx create
ARC_DEPLOY=staging aws-vault exec arc-staging -- npx deploy
```

and then, using an IAM role in a different AWS account, create and re-deploy to production:

```
ARC_DEPLOY=production aws-vault exec arc-production -- npx create
ARC_DEPLOY=production aws-vault exec arc-production -- npx deploy
```

Right now, `npx create` creates assets for both staging and production at once, so there is no way for these to live in different accounts. Assets that must have globally unique names, like S3 buckets, are especially problematic because if you attempt to deploy to one account and then another, the two accounts will conflict (see #174).

**Comment by brianleroux** [comment]
yeaaaaaaa, interesting use case. need to think on this some more but I'm into it. the more granular the better. first q: is this 1 Amazon Account with >1 Amazon Users (?)

**Comment by sentience** [comment]
Not entirely sure what you mean. Our company has a primary Amazon account that all our users have user accounts (with passwords) in, and then we have secondary accounts (production, staging, sandbox, etc.) that have IAM roles that the users in the primary account are allowed to assume. A manual AWS Console workflow for one of our users is logging into the primary account (which is mostly empty), and then switching to their role in the account where they want to work. For scripted workflows on the command line (like arc), we use [aws-vault](https://github.com/99designs/aws-vault) to run commands _as_ those roles (as shown above).

Given all that, I think the answer to your question is no, it's not 1 Amazon account. It's two Amazon accounts (one for staging and one for production). As far as users, I'm using aws-vault to log in as the same user in both cases, but aws-vault uses that user to request a set of temporary credentials for my IAM role in one of the two accounts, and run arc commands with those credentials.

Hope that makes sense!

**Comment by sentience** [comment]
(Caught a typo in my original post. Edited the second set of commands to show the `arc-production` role we use to deploy to our production account.)

**Comment by brianleroux** [comment]
ok, interesting, I think we can make this work but we'd need to give more context to arc. currently we assume one AWS_PROFILE equals one app. 

```
@aws 
profile smallwins
region us-west-2
```

…in this way of thinking we'd want to uniquely assign profile to each stage of resources:

```
@aws
staging
  profile smallwins
  region us-west-2
production
  profile smallwinsprod
  region us-west-1
```

Clean and reasonable!

Next q is, how would global resources work: s3 buckets and dns seem the relevant bits (tho certain I'm probably missing more). I think `@static` can be backwards compatible if we feel safe to assume that when `npx create` ran it created resources in the right places:

```
@static
staging bucket-owned-by-staging-profile
production  bucket-owned-by-staging-profile
```

So thats cool!

`npx dns` creates a certificate in AWS Certificate Manager and two Custom Domains in API Gateway. We leave the CNAME part up to you. If you run `npx dns route53` we do all of that automatically including nameservers, and apex aliases but we'd need to figure out how to disambiguate which account is responsible for those things. Could be a new `route53` key in the `.arc` file:

```
@aws
staging
  profile smallwins
  region us-west-2
production
  profile smallwinsprod
  region us-west-1
route53 smallwins
```

The rest of the workflows that would need addressing: `audit`, `config`, `create`, `deploy`, and `inventory` …I think are pretty easy. We'd just need to be sure the right profile was being assumed at the right times! 

WDYT?

**Comment by sentience** [comment]
While that does look workable, it adds a lot of complexity to the `.arc` file, and would require all members of a team to standardise on their AWS profile names (which we do not yet, although this could be possible).

Is it impractical to support deploying only the staging or production infrastructure using an environment variable?

```
ARC_DEPLOY=production AWS_PROFILE=smalllwins npx create
ARC_DEPLOY=production AWS_PROFILE=smallwinsprod npx deploy
```

**Comment by ryanblock** [comment]
After a lot of consideration, we think this use case can and would be best handled by our upcoming support for CloudFormation. Please feel free to reopen if you'd like to propose a different path, and thanks for reporting!

**Comment by sentience** [comment]
@ryanblock I don't know the scope or direction of the upcoming CloudFormation support. If it's an escape hatch that lets you define your own custom infrastructure, then I'd worry that we would have to lose all the convenience of Arc's opinionated patterns just because we want to deploy staging to one AWS account and production to a different account. Eager to see how it shapes up, though!

**Comment by ryanblock** [comment]
We don't yet have specific scope on the CloudFormation export functionality, but the broad goal is to make it super easy to export your Arc app as CloudFormation (think `npx inventory --export` or something along those lines).

As such, spinning that project up within another account will be as easy as spinning up CloudFormation (which, admittedly, is not as easy as spinning up projects in Arc), and would be something that could probably be easily scripted.

Looking at this feature request from a pure Arc impl perspective, the complexity necessary to accommodate this use case (outside of CF) is pretty massive. It's certainly not impossible, and we're always open to PRs, but this hasn't been a frequent ask or a priority for us, and I we think we'll generally meet this need (and others!) with CF. Hope that helps!
