### ISSUE TITLE
Enable additional runtimes

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#176]
Now that we are dep free by default we should enable the Python, Go, Java, C# runtimes. This would be a per function optin using `.arc-config` with a new key `runtime` with a value of:
- `java8`
- `go1.x`
- `nodejs8.10` (default)
- `python3.6`
- `dotnetcore2.1`

Example `.arc-config`

```
@aws
timeout 900 # max timeout ;)
runtime java8
```

**Comment by ryanblock** [comment]
This is the most a new GitHub Issue has made me happy in a long time.

<img src="https://media.giphy.com/media/l4HodBpDmoMA5p9bG/giphy.gif" width=300>

**Comment by ryanblock** [comment]
→ #183
