### ISSUE TITLE
New command: logs

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#177]
Pretty print logs from a lambda

`npx logs src/http/get-index`

**Comment by mikemaccana** [comment]
Woo! A shorthand version for regular request/response routes would be cool too `npx logs get-index`

**Comment by brianleroux** [comment]
like that idea; shipped the verbose version and will leave this open to remind myself (or someone!) to tackle

**Comment by brianleroux** [comment]
(closing for now but have at it if you wanna tackle!)
