### ISSUE TITLE
Minimally-viable static site powered by arc

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#180]
**Describe the bug**
I was following the static assets guide (https://arc.codes/reference/static), which references the following `.arc` file:

```
@app
testapp

@static
staging test-bukkit
production main-bukkit
```

I wanted to try out a very very simple site with arc to play around: nothing more than a static site. When I run `npx create`, indeed the two buckets are created. But running `npx deploy` doesn't seem to upload any static assets to these buckets.

I have a very simple `index.html` file in my project:

```
<html>
    <head>
        <title>hey</title>
    </head>
    <body>
        <h1>yo</h2>
    </body>
</html>
```

I tried storing the above `index.html` file in both the `public/` and `.static/` subdirs of my arc project before running `npx deploy` to no avail (the confusion around where to store static assets was filed as a separate documentation issue here https://github.com/arc-repos/arc.codes/issues/45).

**To Reproduce**
1. Use the above super simple `.arc` file
2. Run `npx create`. S3 buckets created. Sweet.
3. Run `npx deploy`. S3 buckets are empty. 😢 

**Expected behavior**
When running `npx deploy`, I expect my static assets to be deployed to the staging S3 bucket.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**
Output from running `create` and `deploy` tasks on my machine:

```
➜ npx create

        ARC_APP_NAME yo
          AWS_REGION us-west-1
         AWS_PROFILE default

                Node 10.4.1
                 npm 6.1.0
                .arc 3.6.0

➜ npx deploy

        ARC_APP_NAME yo
          AWS_REGION us-west-1
         AWS_PROFILE default

                Node 10.4.1
                 npm 6.1.0
                .arc 3.6.0
```

Both commands exited with a 0 exit code.

**Comment by mitchh** [comment]
Yeah; it seems things fail silently unless you have at least one lambda.

**Comment by brianleroux** [comment]
Verified in architect/architect@latest. It doesn't fail so much as we didnt expect ppl to use lambda functions to build static websites… but we're working to make this particular use case easier! Should have a patch ready shortly.

**Comment by brianleroux** [comment]
not weird! very common approach. I'd say once you get a bit further the static assets part starts to look / feel pretty janky and you'll want to use lambda for everything (including serving static content you dynamically render without a build step). now that's weird! that's where I think we'll get ppl … but we need to make that transition easier and making static assets and current generation build chains seamless if we want folks to get down on the dynamic/trusted process approach.

**Comment by brianleroux** [comment]
talkin it through w kj; we're going to change things

`npx deploy` deploys all lambdas (if defined) and `/public` (if `@static` is defined)
`npx deploy static` deploys just `/public` (aliased to `npx deploy public` and `npx deploy /public`)
`npx deploy lambdas` and `npx deploy functions` just deploys functions 
`npx deploy src/http/get-index` deploys just that function 

All command variously accept an env modifier. Eg:

- `npx deploy production` deploy everything to prod
- `npx deploy static production` deploys `/public` to the production bucket configured in `@static`

etc

LMK what u think!

**Comment by filmaj** [comment]
Awesome, makes sense!

Sounds like `npx deploy` optionally accepts an argument that specifies which parts of the app (as defined in the `.arc` file) to deploy, and that this can be of varying scope. i.e. `deploy static` deploys out what is defined under `@static` in the `.arc` file, or I can go `deploy static production` to deploy just to the prod bucket under static

Would a similar argumentation be done for other parts of the arc file? _checks notes_ like queues, tables, indices, events, slack, etc.?

**Comment by brianleroux** [comment]
Could be! Right now we bulk deploy all functions because its so fast (unless you explicitly give us a path to a lambda then we deploy just that eg:`npx deploy src/http/get-index`).

**Comment by kristoferjoseph** [comment]
@filmaj having each pragma in the `.arc` file be a deploy flag is a really great idea!
Would really reinforce the `.arc` file as a map of your app.
`npx deploy` would be the same as `npx deploy app` for the `@app` pragma which would deploy all the things.
`npx deploy static` for the `@static` pragma
`npx deploy events` for the `@events` pragma
and they all would allow a staging or production specifier flag.

very logical to my mind.

**Comment by brianleroux** [comment]
love it! ya, would be happy to pair and get you up to speed. this would be a pretty easy first commit. (once we merge https://github.com/arc-repos/architect/pull/179 which I expect should be today-ish!)

**Comment by brianleroux** [comment]
closing this in favor of 185 (pure static arc apps now depoy!)

**Comment by filmaj** [comment]
Yay! It works! Thank you!
