### ISSUE TITLE
Can't see codeship pull request CI/build details

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#184]
**Describe the bug**
When I try to click the red or green checkmarks in pull request views to see the results of CI (i.e. https://app.codeship.com/projects/311665/builds/38089118), I get a codeship error 'no access' page.

**To Reproduce**
Visit e.g. https://app.codeship.com/projects/311665/builds/38089118

**Expected behavior**
Can see CI build results.

**Screenshots**
<img width="316" alt="screen shot 2018-10-30 at 7 19 16 pm" src="https://user-images.githubusercontent.com/52645/47760226-bf642e00-dc78-11e8-9552-820bf68051f6.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac OS 10.13.6
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 70.0.3538.77

**Additional context**
Mostly I was just making sure that there was nothing more than tests + linting running to approve pull requests 🤷‍♂️

**Comment by brianleroux** [comment]
yeah, this is how codeship works / can make you a member of the team to see it if you're into it (also down to explore another CI/CD system for this

**Comment by filmaj** [comment]
Whatever works for you. Kinda shitty for an open source project to have build details behind a wall. As an external contributor it sucks not knowing what failed a build, or even what a build does/is.

**Comment by filmaj** [comment]
I'm partial to travis ci myself 🤷‍♂️

**Comment by brianleroux** [comment]
yea this is a legacy of begin extraction; codeship is pretty nice for a commercial product. (all it does is `npm run lint && npm t` which I'd hope you'd see locally first eh.)  

I'm fine w travis if you want to send the PR to add it!

**Comment by brianleroux** [comment]
oh now I remember! its because we need aws secrets/keys to run the tests (and in the case of the docs to deploy them)

**Comment by ryanblock** [comment]
I think Travis lets us set an arbitrary amount of encrypted secrets/keys/env vars that can't make their way into build output, gonna do a little digging on this. Codeship has some customer migration deadline coming up in Jan 2019, so this is prob good timing to evaluate anyway.

**Comment by filmaj** [comment]
Can confirm travis supports this. I have my AWS keys in e.g. [my personal site](https://github.com/filmaj/filmaj.ca/commits/master), which deploys out to AWS on every commit to master (example of a build from that is [here](https://travis-ci.org/filmaj/filmaj.ca/builds/438866989?utm_source=github_status&utm_medium=notification)). Near the top of the build log (around lines 425) you can see that the relevant AWS env vars are hidden:

```
Setting environment variables from repository settings
$ export S3_ACCESS_KEY_ID=[secure]
$ export S3_SECRET_KEY=[secure]
$ export CLOUDFRONT_DISTRIBUTION_ID=[secure]
```

... which I control via travis' UI.

**Comment by filmaj** [comment]
More info on that is available here: https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings

**Comment by ryanblock** [comment]
I'm starting in on this, please stand by! Will post back shortly.

**Comment by ryanblock** [comment]
Gonna be a minute. Travis doesn't like this old version of [`progress`](https://www.npmjs.com/package/progress); recently tried upgrading `progress` in Architect, and it broke things horribly, so I'll have to figure out a workaround. This week!

**Comment by filmaj** [comment]
Oh man that totally gives me flashbacks - I remember having the same issue and I ditched progress bars completely in my project because of this! The progress support for Linux is poor IIRC

**Comment by filmaj** [comment]
Not that I know of a better other option but the fact that that module has zero tests speaks volumes...

**Comment by brianleroux** [comment]
its basically one file and does a whole lot more than we need it to; we should fork it out and take over the dep

**Comment by filmaj** [comment]
Nice!

**Comment by ryanblock** [comment]
For those playing along at home:
- https://travis-ci.com/arc-repos/architect
- https://travis-ci.com/arc-repos/arc.codes
- https://travis-ci.com/arc-repos/arc-data
- https://travis-ci.com/arc-repos/arc-functions
