### ISSUE TITLE
deploy specific pragmas via cli

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#185]
**Describe the bug**
Not so much a bug but an enhancement suggestion. As per discussion in #180, it came up to allow the `deploy` command to take specific pragmas to deploy out as a parameter. As @kristoferjoseph put it

> `npx deploy static` for the `@static` pragma
> `npx deploy events` for the `@events` pragma

When no pragmas are specified (e.g. `npx deploy`), it is assumed to be the `@app` pragma, that is, the whole thing.

Furthermore, the above may be qualified by an environment. That is

    $ npx deploy static production

... would deploy the `@static` pragma - but only to the production environment.

**Implementation Questions**

I was looking at how to implement this, and hit a snag: I found it difficult to try to write tests for the [deploy CLI handler](https://github.com/arc-repos/architect/blob/master/src/deploy/cli.js). The tests for the deploy module are kind of light - I wouldn't feel comfortable without adding tests for this.

The CLI module feeds a callback that contains the majority of the logic that would need to be modified, but that callback is 'hidden' away behind an `init` utility method that deals with CLI specifics (that I think can be ignored for the purposes of this enhancement). 

Any advice/guidance/direction on how to proceed with a possible refactor? I think the simplest would be to factor out the `_init` callback into its own module. It would take process args as arguments, and I could add tests there for this functionality.

**Comment by brianleroux** [comment]
Just updated this morning so the code is a bit easier to follow. All the CLI arguments stuff is isolated to that file; thinking on it we probably want a set of tests for just testing CLI stuff (in addition to module tests). The whole testing story is a bit of a mess and I'd to love to just talk it through with you. (Legacy again of our extraction/migration.) Down for a zoom meeting sometime this week?

**Comment by filmaj** [comment]
Nice! I'll take a look tonight at the updates.

A zoom call sounds good. I have lots of time Friday - that work?

**Comment by brianleroux** [comment]
yar, I'm cool doing this in the open so if anyone wants to join we'll be on Zoom at 11am PT on Friday

https://zoom.us/j/2313939839

**Comment by filmaj** [comment]
Yarr the code's much cleaner now, nice work.

**Comment by filmaj** [comment]
Looks like I missed ya B! No worries. Spoke briefly with the team and @kristoferjoseph mentioned that some more efforts on expanding the test suite could be used, so maybe I start there as a means of familiarizing myself with the code more and expanding the safety net under us before moving to tackle larger changes such as the one in this issue.

I'll play around and send a pull request with my thoughts around this as a means to kick that convo off.

**Comment by brianleroux** [comment]
Super sorry missed u mang / flight today was not when I would have expected it be alas

**Comment by brianleroux** [comment]
shipped in `4.4.1` 

to try it out `npm i @architect/architect@rc1`

**Comment by filmaj** [comment]
So awesome! Thank you!
