### ISSUE TITLE
"Error: From should be a file or directory" during 'npx deploy' on 4.1.1

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#186]
I've updated https://github.com/arc-repos/arc-example-login-flow to use arc 4 per https://github.com/arc-repos/arc-example-login-flow/pull/1 but an npx deploy fails with: 

    $ npx sandbox
                                                                
            ARC_APP_NAME loginflow                               
              AWS_REGION us-west-2                               
            AWS_PROFILE xxx                                     
                                                                
                    Node 8.12.0                                  
                    npm 6.4.1                                   
                    .arc 4.1.1                                   
                                                                
    ✓ @tables created in local database
    ✓ src/shared copied to lambda node_modules/@architect/shared
    C:\Users\mikem\OneDrive\Documents\arc\arc-example-login-flow\node_modules\@architect\architect\src\
    sandbox\start.js:51
        if (err) throw err
                ^

    Error: From should be a file or directory
        at C:\Users\mikem\OneDrive\Documents\arc\arc-example-login-flow\node_modules\cpr\lib\index.js:3
    12:29
        at C:\Users\mikem\OneDrive\Documents\arc\arc-example-login-flow\node_modules\graceful-fs\polyfi
    lls.js:284:29
        at FSReqWrap.oncomplete (fs.js:152:21)

architect 4.1.0, Windows 10.

**Comment by mikemaccana** [comment]
Adding some login, the real err is

    ENOENT: no such file or directory, stat 'C:\Users\mikem\OneDrive\Docume
nts\arc\arc-example-login-flow\src\views'

**Comment by brianleroux** [comment]
ah, weird...just checked out and ran `npm update && npx hydrate update && npx sandbox` and it 'just worked' but I have src/views/readme.md ...is that dir there for you?

**Comment by mikemaccana** [comment]
You just added the file 16 mins ago! https://github.com/arc-repos/arc-example-login-flow/commit/e8c4b4d2a8a5a70030650693f2b82e72952b9b98

I sent a PR but you can close it since it's already done,

**Comment by brianleroux** [comment]
LOL sorry!!! I updated/tested on my mac to verify there and I guess it generated it then
