### ISSUE TITLE
static deployment: only upload changed files

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#187]
**Describe the enhancement**
So I am iterating on my little arc app now, just playing around with `@static` pragmas. It's fun!

One thing I noticed is that, as I removed files from the `public/` folder, they would still be kept on the S3 buckets after a deploy. It would be good to support 'diff' deploys (I believe this was brought up in #151 as well), that is, if files are not present in `public/` but present on the S3 bucket, they would get deleted from the S3 bucket during a deploy.

In a similar vein, deploy should only deploy files that were changed. I believe we can do this by comparing the ETag values of files in buckets and only upload the files that have differing tags.

The [s3-deploy](https://www.npmjs.com/package/s3-deploy) package and its `--preventUpdates` (etag comparison) and `--deleteRemoved` flags should be able to provide a majority of the above functionality. Oh, and it also supports CDN invalidations for changed files - which is another future feature request I will file 😇.

What do y'all think? Should this be desirable, this is another one I could take a stab at working on.

**Comment by brianleroux** [comment]
into doing everything you said here except adding that module (it would add 50mb; nearly 50 modules some of which could cause problems for bundling into an executable)

but I'm stoked to reimpl that with vanilla aws-sdk calls anyhow! bet we could do all that w far less…stuff.

**Comment by brianleroux** [comment]
also: don't think we want to every auto delete based on /public. if two ppl are working on different trees they'd could deleting each others WIP. deletion should exist, and probably be an explicit step…which isn't great but also wouldn't result in any perception that we lost anyones work

**Comment by filmaj** [comment]
OK, that all makes sense.

Re: deletion, perhaps put that behind a deploy flag? `npx deploy static --delete-removed` or some such?

**Comment by brianleroux** [comment]
I'd be cool w just `--delete` or maybe `--sync` ? How do other tools do this?

**Comment by filmaj** [comment]
`rsync` does `--delete` - I like it.
