### ISSUE TITLE
what is the difference between create, deploy and hydrate commands? 

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#191]
> question is more around the intention behind separating these commands. What differences do each of these abstract away? This is purely educational for myself to figure out what (future) functionality should exist in which module. - @filmaj asks

## `npx create`
`npx create` creates infrastructure defined by `.arc` and ONLY creates. it never deletes. It also only creates a thing if it does not yet already exist …which is to say: create is safe to run over and over again. Create is meant to be run repeatedly as you iterate. 

As your architecture evolves so will the infra. We also don't want to blow away stuff we already created because that is a waste of time and we respect your time. 

## `npx deploy`

The 🔑  difference between create and deploy is that deploy is a destructive write. `npx deploy` will remorselessly overwrite the function code to the target lambdas and, likewise, completely overwrite whatever static assets are currently on the target s3 buckets. Deploy assumes you know what you are doing and you want us to be fucking quick about it. 

You could also say `npx deploy` is the modern FTP. =) We do a few nice things in there too. We verify the assets, reset the node_modules to whatever `package-lock.json` says and zip up the contents. We left room for further steps (like transpilation and bundling) but I am more interested in solving runtime agnosticism first. 

## `npx hydrate`

Hydrate runs `npm i` on your lambdas (or if you run `npx hydrate update` it will run `npm update` on your lambda functions. primary use case: downloading an Architect project from github and you want to bootstrap without running create/deploy first. This is the flow today:

```bash
git clone [some repo with a .arc] myproj
cd myproj
npm i
npx hydrate
npx sandbox
```

Pretty nice… but you can see now how we can make that way nicer by removing the node dep and distributing a binary:

```
curl arc.codes/install.sh | sh
git clone myproj
cd myproj
arc sandbox
```

**Comment by filmaj** [comment]
OK, so create is idempotent and non-destructive, deploy is destructive, and hydrate updates lambda _dependencies_ only - not source code. Do I have that right?

I also noticed that there seems to be variable behaviour in `create` (and looks like `sandbox` as well) based on the presence or absence of the `ARC_LOCAL` env var.

Couple questions to help me clarify last things here:

1. Is deploy a superset of create? That is, does deploy do everything create does, plus destroying, or is that not entirely accurate?
2. Does hydrate happen during create or deploy? Or does that need to be explicitly run (presumably only after create is run)?

**Comment by brianleroux** [comment]
> OK, so create is idempotent and non-destructive, deploy is destructive, and hydrate updates lambda dependencies only - not source code. Do I have that right?

Yup, exactly. 

> I also noticed that there seems to be variable behaviour in create (and looks like sandbox as well) based on the presence or absence of the ARC_LOCAL env var.

Yes! Initially the thing that became Architect only worked against the cloud. We slowly moved towards local only stuff. So if you wanted to create an arc project code ONLY (and not infra) `ARC_LOCAL=yas npx create` would do that. We recently had a bit of thrash from Windows users with environment variables so now `npx create local` works. (Another legacy of our early dev was using env vars as switches … it was deliberate because we didn't know what command line options we wanted and env vars are a nice way to trial stuff before officially baked.) In the case of sandbox the ARC_LOCAL flag is a bit unfortunate. We need to tidy that up. Basically it exists to let the dynamodb connection logic know 'we are working on a local machine so you are going to connect to the real database' with the syntax `ARC_LOCAL=1 NODE_ENV=staging npx sandbox` starts up the local webserver (because ARC_LOCAL exists) but uses the live dynamodb staging connection logic. This is incredibly helpful in dev! the newer syntax is `npx sandbox --staging` (much nicer! but I haven't extensively tested…the flags branch landed recently!)

**Comment by brianleroux** [comment]
whoops! hit return too soon furthermore: 
> Is deploy a superset of create? That is, does deploy do everything create does, plus destroying, or is that not entirely accurate?

No, deploy is totally different. It does SOME of the same things from a dev experience tho. Both inflate deps. Create does deploy initial lambda code (inflated with default deps) and no initial content is uploaded to s3 when buckets are created they are just 'initialized' with default permissions so you can access them thru a web browser.  

> Does hydrate happen during create or deploy? Or does that need to be explicitly run (presumably only after create is run)?

Yes sort of! Create runs `npm i` before uploading initial default code. Deploy runs `npm ci` which only pulls stuff explicitly from package-lock.json (and cached so its acceptably fast). We'll need to revisit these code points for Python and others soon.

**Comment by filmaj** [comment]
What do you think about folding some of the info in this issue as comments into the code in relevant spots? Just thinking about how to capture the useful info in here longer term for other contributors..

**Comment by brianleroux** [comment]
Solid idea! Even docs on the website ?

**Comment by filmaj** [comment]
![dbcutoo](https://user-images.githubusercontent.com/52645/48217012-d75c4180-e34b-11e8-9a9f-d30627446c5b.png)

I will take a stab at PRs for this issue.

**Comment by filmaj** [comment]
Had another thought as I was thinking about how to suggest some changes capturing the knowledge in this thread.

The `create`, `deploy` and `hydrate` commands all make changes to infrastructure. Another command that makes changes to infrastructure: `npx inventory nuke` and its variations. What do you think about compiling an overview of how these commands work together in a workflow as a new "guide"? We already have a guide called "working locally", so this new guide could be a complement to working locally. Maybe "deploying infrastructure" or some such? This guide could capture the (sometimes subtle) distinctions between the four infrastructure-modifying commands.

Another thought as I reviewed the existing guides. There's a "working locally" guide and a "static assets" guide, and within the static guide there's a section called "Working locally with public". Feels like sections are overlapping but spread out across guides. Maybe there's a way to clarify workflows and usage by reorganizing a little bit? Thinking out loud mostly.

**Comment by brianleroux** [comment]
Oh yes pls I love that!
