### ISSUE TITLE
Static assets not reachable after deploying an http route

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#192]
**Describe the bug**
First `create` an arc of only static assets, load static assets just fine on staging URL. Then add one http api,  run `create` again, now you are not able to load static assets on staging URL.

**To Reproduce**
```
> cat .arc
@app
recipeapp

@static
staging recipeapp-staging
production recipeapp

@http
post /recipe

> cat public/index.html
<html lang="en"> <head> <title>yoo</title></head> <body> <div id="root">hi</div></body></html>

> npx create

        ARC_APP_NAME recipeapp
          AWS_REGION us-west-1
         AWS_PROFILE default

                Node 10.4.1
                 npm 6.1.0
                .arc 4.1.3


✓ Successfully deployed
https://vvynbk99aa.execute-api.us-west-1.amazonaws.com/staging

> curl -v -X POST https://vvynbk99aa.execute-api.us-west-1.amazonaws.com/staging/recipe
< HTTP/2 200
< content-type: text/html; charset=utf8
< content-length: 21
< date: Thu, 08 Nov 2018 04:05:20 GMT
< x-amzn-requestid: 823ecfdb-e30b-11e8-ac5f-9b1f48ea4f6e
< x-amz-apigw-id: QBlgEHyVyK4FaPQ=
< x-amzn-trace-id: Root=1-5be3b600-fd568ec4e4e221563134c722;Sampled=0
< x-cache: Miss from cloudfront
< via: 1.1 b90b6784a39d061a6bbabe5f3c77f00d.cloudfront.net (CloudFront)
< x-amz-cf-id: jlx6vcDyuPaeuS7Nt4-3HLnvRCkA0rTMac-DgVCHdAP3yQ5Mkd1eDQ==
<
* Connection #0 to host vvynbk99aa.execute-api.us-west-1.amazonaws.com left intact
<h1>Hello world!</h1>%

> curl -v -X GET https://vvynbk99aa.execute-api.us-west-1.amazonaws.com/staging
< HTTP/2 403
< content-type: application/json
< content-length: 42
< date: Thu, 08 Nov 2018 04:06:33 GMT
< x-amzn-requestid: ad92bb43-e30b-11e8-a690-117e8170b078
< x-amzn-errortype: MissingAuthenticationTokenException
< x-amz-apigw-id: QBlrbFy1SK4FQfA=
< x-cache: Error from cloudfront
< via: 1.1 d64756b4df47ce24d6c62b5a8de97e87.cloudfront.net (CloudFront)
< x-amz-cf-id: IEx86pIsdLDauqDR0gDsg4MxSXYusc9DDf3CjL_sdV2NvfO8nYokAQ==
<
* Connection #0 to host vvynbk99aa.execute-api.us-west-1.amazonaws.com left intact
{"message":"Missing Authentication Token"}%
```

**Expected behavior**
Where should I expect the index.html static content to exist? Issuing a GET to / yields the HTTP 403 and missing auth token error above. The lambda works fine though (again, see above). Maybe something to do with session tables? I saw those get automatically generated for me.

I would really like to keep my client and server code separate - a PWA up front with a lambda-powered API in the back. No server-side rendering for me. Perhaps I'm doing this wrong?

Interestingly enough this same `.arc` file _without_ any `@http` routes defined deployed fine and could be browsed via the staging URL returned when running `npx create`. Maybe that is part of this: that I ran `npx create` once for a `@static` pragma only arc app, then added an `@http` pragma, then ran `npx create` again.

**Desktop (please complete the following information):**
mac OS 10.13.6

**Comment by filmaj** [comment]
I dug a bit more into this and I think this one can be filed under "I'm doing it wrong."

1. I was confused again between `create` and `deploy` commands.
2. The URL that static assets exist at is an S3 bucket URL, whereas the URL the lambda HTTP API exist at is a execute-api URL.

My goal is to have GET requests, by default, hit static assets sitting in an S3 bucket (or a CloudFront dist that sits in front of the S3 bucket), and reserve a specific set of paths for a lambda-backed HTTP API.

I'll experiment with API Gateway on my end to see if this kind of setup is even doable. Gonna close this, sorry for the noise.

**Comment by filmaj** [comment]
It _seems_ like what I want is possible, based on this doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html

Playing around with that but failing so far. Will keep chipping away.

**Comment by brianleroux** [comment]
Alright. Cors be damned I'm coming for u. (Will stand up an example repo and document how-to.)

**Comment by brianleroux** [comment]
found a bug in our cors vtl…fixed it in ur branch and just looking into an unrelated sandbox bug then I aim to merge and ship that!

**Comment by filmaj** [comment]
So I'm not sure what was fixed but it didn't help me haha. Agai:n I think I'm doing it wrong. Let me walk through what I tried, what I manually set up with AWS as an attempt to work around it, and my thinking moving forward.

I want to set up an HTTP API, powered by lambdas, _alongside_ a set of static assets comprising a thick clientside app.

Initially I wanted to have `GET /` simply direct to an S3 bucket (or CloudFront dist) to return back the clientside app HTML/CSS/JS/static assets. I then tried to "augment" the S3-backed static routes with an HTTP route pointing to a lambda. Out of the box this didn't work with arc because, from what I can tell, the `/` route is _required_ under the `@http` pragma, and arc sets it up to point to a lambda. 

So then I tried to set this up manually in AWS. I could do it - sort of, but it looks like there's a limitation in API Gateway. In API Gateway I set up the `GET /` route to integrate with S3 and override the path so that it sends the request to a specific bucket's `index.html`. That works great. I then tried to set up an additional route (er, API Gateway "resource") to cover arbitrary paths to static assets and direct them to the same bucket. The issue then became that compound paths (paths involving subdirectories) weren't recognized by API Gateway. Finally I tried using the [catch-all path variables in API Gateway Resources](https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/), i.e. `/{staticpath+}`, but unfortunately API Gateway won't let me integrate this request with S3 or CloudFront. Womp Womp.

My next attempt is to segment the API vs. clientside app approach by domain. That is, have one arc app that is purely static assets, backed with a domain like mysweetapp.com, and another arc app that is purely HTTP functions comprising a CORS-friendly API, backed with a domain like api.mysweetapp.com.

Curious on your thoughts @brianleroux. I know you recommended to me earlier to embed session and auth tokens directly into clientside app HTML (I believe you called it trusted process), but that breaks the clientside app / serverside API delineation that is very important to me.

**Comment by brianleroux** [comment]
Fronting s3 API Gateway sure sounds painful! I definitely wouldn't do that. Your last option (S3 is one domain and your API is another) makes more sense. Just published a blog post about cors which should help. 

Blog
https://blog.begin.com/enable-cors-on-your-serverless-application-with-a-single-boolean-e784fc061b22

Demo

https://brianleroux.github.io/cors-final-boss/

Source
https://github.com/brianleroux/cors-final-boss/

It'll make working with session harder...which idk maybe you don't need.

**Comment by filmaj** [comment]
Yeah that's exactly the kind of setup I want to do. Thanks for the link.

I'll play around further that way.

P.S. do you foresee issues with having two separate arc apps each with an `@dns` pragma, but one being a subdomain of the other (i.e. `app.com` and `api.app.com` ?)

**Comment by brianleroux** [comment]
no problem however `@domain` pragma currently only works on the weird combo of things you need to do to generate API Gateway CloudFront distributions. (I can walk u thru it.) We do not do anything for s3 buckets… yet. 

I'm open to working through what that looks like.

In an `.arc` file today:

```
@app
myapp

@static
staging foo-bukkit
production bar-bukkit

@domain
some.com

@http
get /
```
Generates:

- A certificate for `*.some.com` (which it will then use for generating cloudfront distributions)
- https://staging.some.com pointing to the staging cloudfront distubution for src/http lambdas
- https://some.com points to a production cloudfront distribution for src/http lambdas
- and we leave mapping the S3 bucket DNS to you…but we only use them for images and …static stuff and use a lambda to server js assets so we can dynamic transform, (or not) and cache, etc

I could see enhancing this w cloudfront distributions and dns for buckets under a subdomain like `static`. So the following `.arc`:

```
@app
myapp

@static
staging foo-bukkit
production bar-bukkit

@domain
some.com

@http
get /
```
generates
- A cert that covers both `*.some.com` and `*.static.some.com` (no cors needed then eh!)
- https://staging.some.com
- https://some.com
- https://staging.static.some.com
- https://static.some.com

But this again treats static assets as… not the root apex domain which I acknowledge most current generation static asset/frontend workflows think you want.

I am not as excited about an s3 bucket being 'the origin authority' because it can't do httponly cookies nor does it possess a trusted backing process (so accessing databases and stuff requires temp credentials on leaked to the client). Is it insecure? No. Can the security be better? Yes. So the I think I'd like the happy path to continue to be http lambdas map to / because that is a higher likelyhood scenario than the current gen thinking.

> Consider: static asset flows are faster today but very little indicates lambdas will always be slower. Once they have parity on speed its unlikely you'll want to continue with a less capable and less secure apex. 

I could see doing something more elaborate with dns that lets you treat it in a more granular fashion at the expense of slightly more verbose config: 

```
@app
myapp

@static
staging foo-bukkit
production bar-bukkit

@domain
static
  staging staging.some.com
  production some.come
http
  staging staging.api.some.com
  production api.some.com

@http
get /
```

WDYT?

**Comment by filmaj** [comment]
Thanks for that @brianleroux. Just wanted to say that my silence on this topic isn't disagreement so much as chewing through / processing all the practices and approaches that you and your team have demonstrated to me (to which I'm super grateful!). I realize that my previous understanding of what constitutes a dynamically generated asset vs. a static one gets flipped completely upside down by arc.

I had a chat with @kj on Friday where he showed me how y'all are building webapps with arc. My old concepts of static vs. dynamic and client vs. server are really getting challenged. While I still like the separation of concerns between client and server code, I feel I am becoming more convinced of throwing out that puritan view and reaping the benefits of 'cheating' by mixing the two.

The one doubt that keeps lingering in my mind is speed, of serving static content in a let's-say classic manner by e.g. S3+CloudFront vs. having such assets be served by Lambda directly. To further add to my soulsearching and confusion I can see a future where that is not a concern. Who knows, maybe it is not a concern today already.

As I mentioned to @kj I think my next step is going to be to prove or disprove that concern by putting together a comparison app, perhaps compare my personal site to a lambda-backed arc equivalent.

**Comment by brianleroux** [comment]
The delta is pretty harsh on fat Lambdas above 5mb compressed. Below that you coldstart subsecond. It's not 10ms ....yet. but it will be eventually. Zeit is now following our thinking here too. (Only a couple of years late!;)
