### ISSUE TITLE
question: async function support in arc.http

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#193]
per https://github.com/arc-repos/arc-example-login-flow/issues/3

not sure how to impl and would love feedback @mikemaccana !

maybe something like

```javascript
let arc = require('@architect/functions')

// normal fun
function home(req, res) {
  res({html: 'hi from home'})
}

// async fun
// expect the second param to be 'next' if the function is an instance of AsyncFunction ???
async function log(req, next) {
  console.log('idk?')
  next()
}

exports.handler = arc.http(log, home)
```

**Comment by austinkelleher** [comment]
Should we allow using `await next()`? This is the pattern for Koa middleware.

**Comment by brianleroux** [comment]
oh I like it! but should we support the whole idea of `context` then too ?

**Comment by austinkelleher** [comment]
Good question. I think we should so that we can access different information in middleware. It would be particularly interesting if the API was consistent such that we could use async Koa middleware inside of arc. Not sure how realistic that is, but would be pretty awesome.

**Comment by mikemaccana** [comment]
Express 5 supposedly supports async/await, but just in terms of having async route functions - you can use await inside them, but you're still expected to call `response()`. See https://github.com/pillarjs/router (which Express 5 uses) for details. This isn't ideal- functions should return values, like the way Arc does already when you're not using middleware. 

Koa middleware uses `await next()` (this article)[https://medium.com/netscape/mastering-koa-middleware-f0af6d327a69] provides a good overview but TBH I don't think this is ideal either. Koa isn't that popular that there's a huge ecosystem to take advantage of yet.

A series of middleware tasks is - a series of middleware tasks. Series of things in order are best represented as Arrays. This allows us to get rid of `next()` entirely:

    let arc = require('@architect/functions')

    // expect the second param to be 'next' if the function is an instance of AsyncFunction ???
    async function log(request, next) {
        console.log('idk?')
        if ( request.someKey === someValue ) {
            // Return a response to respond, ending further middleware processing 
            return({
                status: 403,
                html: 'access denied'
            })
        }
        // Return anything other than a response to continue processing
    }

    async function home(request) {
        return({html: 'hi from home'})
    }


    exports.handler = arc.http([log, home])

**Comment by mikemaccana** [comment]
Working async middleware! 

	let arc = require("@architect/functions"),
		url = arc.http.helpers.url,
		respond = require("@architect/shared/respond"),
		[print, debug, log, warn, alert] = require(`boring-utils`);

	async function requiresLogin(request) {
		let state = await arc.http.session.read(request);

		if (!state.isLoggedIn) {
			log(`Attempt to access dashboard without logging in!`);
			return respond.redirect(`/login`);
		}
		log(`We're logged in`);
		// return nothing, so middleware continues
	}

	// No async-using middleware (ie, a separate requiresLogin) since that's not done in arc yet https://github.com/arc-repos/architect/issues/193
	async function showDashboard(request) {
		log(`Showing dashboard`);

		let dashboardPage = `
		<body>
			<h1>Dashboard</h1>
			<p>oh hai you are logged in! <a href="/logout">logout</a><p>
		</body>`;
		return respond.makeResponse(dashboardPage);
	}

	function combine(...steps) {
		let combined = async function(request) {
			log(`Running combined function!`);
			var response;
			for (let step of steps) {
				log(`Running step ${step.name}`);
				response = await step(request);
				if (response) {
					log(`Got a result from ${step.name}, finishing...`);
					break;
				}
				log(`Did not get a result from ${step.name}, continuing`);
			}
			log(`Finished combined function!`);
			return response;
		};
		var stepNames = steps.map(function(step) {
			return step.name;
		});
		log(`Combined functions ${stepNames}`);
		return combined;
	}

	exports.handler = combine(requiresLogin, showDashboard);

Same rules as before, ie no modification of the request between middleware items.

**Comment by brianleroux** [comment]
oh dude! I like this a lot… hmmmmmmmmm… wonder if we could make `arc.http` smart enough to know you want this style vs the express-y style (alternatively we could deprec the expressy stuff and move this way)

**Comment by mikemaccana** [comment]
Thanks! 😃 My general feeling is to deprecate the express style in the next major release:

 - One, obvious way to do things is best (not just for users but for maintenance too). This is less complicated than the Express style due to not needing `next()` and also more consistent with regular `await` style routes. Ie, the whole "how do I do middleware?" becomes:

> ## HOw do I do middleware?
>
> Just run `arc.http()` specifying the middleware as arguments. Requests will be run through each middleware in the order they're given to `arc.http()`, with the first middleware to return a value ending the processing. Middleware can return null or any other falsy value to ensure the request continues to be processed.

 - The existing Express-style implementation isn't as 'express-like' as one would think - we don't allow the request to be mutated between middleware. A different signature is a good way of indicating users should have different expectations.

**Comment by mikemaccana** [comment]
Just a quick note **I might have something even better than this**, heading to gym now but will post again in a few hours.

**Comment by mikemaccana** [comment]
OK done. Check the updated example above!

**Comment by mikemaccana** [comment]
Also I've called this `arc.middleware` because it's a little clearer (and also a good break from the older `arc.http` style).

**Comment by brianleroux** [comment]
love it! send a pr to github.com/arc-repos/arc-functions and we'll get that in!

**Comment by mikemaccana** [comment]
Rock and roll. Going to learn tape and send a PR and some tests shortly.

**Comment by mikemaccana** [comment]
I've done this in https://github.com/mikemaccana/arc-functions (see https://github.com/mikemaccana/arc-functions/commit/a383455c1d93faf271863377a4030a045b7d3408) but after `npm i https://github.com/mikemaccana/arc-functions` I can't actually invoke the new code for some reason. 

Even completely removing `.\node_modules\@architect\functions` doesn't even complain in the sandbox when I use a route that runs `arc = require("@architect/functions")`. I think I'm going insane.

**Comment by mikemaccana** [comment]
Everything else was `arc.http.foo` so that seemed logical - is `arc.http.foo` going away?

Happy to, but I'm flying blind if I can't get any errors. It's entirely possible I'm fatigued right now (it's the end of the day here and it's been Rubik's cubes all day).

I'll revert to current upstream, add a console.log or throw an error and see if that works before going any further.

**Comment by brianleroux** [comment]
word! we're doing a big migration this morning so I'll HOPEFULLY be back to give this a go myself this afternoon… 🤞

**Comment by MasterJames** [comment]
It must be installed globally. Try npm uninstall with the -g flag

**Comment by mikemaccana** [comment]
Nah, the cause is the copying that happens during the `npm run build` step:

    console.log(require.resolve("@architect/functions"));
  
    C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\src\http\get-dashboard\node_modules\@architect\functions\index.js

**Comment by mikemaccana** [comment]
So I just realised I misread someting earlier:

@brianleroux said:

> did you install into the function in src/http/ or in the root ?

I thought he was asking about the file I modified in the module (which was also called `/src/http/index.js` coincidentally)

In reality he meant I should install the modified module into `src\http\get-dashboard` (or whatever the route I was testing the middleware with) per https://arc.codes/guides/deps

**Comment by mikemaccana** [comment]
OK all good now, check out the PR at https://github.com/arc-repos/arc-functions/pull/14

**Comment by brianleroux** [comment]
nice, gotta update the changelogs with this next! ❤️ 

(also works for other function types like queues and events eh!)

**Comment by mikemaccana** [comment]
Cool, I'll update the docs too if you don't do it first!
