### ISSUE TITLE
static content 404s in sandbox

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#194]
**Describe the bug**

static content - even the readme.md from the examples - just doesn't seem to be served in sandbox. 

Per https://arc.codes/guides/static-assets:

> Any file added to this public folder will be served (along with any HTTP functions you've defined).

**To Reproduce**

 - arc `4.2.0` #blazeit edition on Windows 10 `10.0.17763.0`
 - The file `public/readme.md` exists
 - `npx sandbox` is run and `Started HTTP "server" @  http://localhost:3333`
 - `http://localhost:3333/public/readme.md` 404s

Am I going nuts?

**Comment by mikemaccana** [comment]
Hrm: 

  let allowed = [
    // images
    'bmp', 'gif', 'jif', 'ico', 'jpg', 'jpeg', 'png', 'svg', 'tif', 'tiff', 'webp',
    // compiled web stuff
    'css', 'htm', 'html', 'js', 'json', 'mjs', 'ts',
    // binaries + archives
    'bz', 'bz2', 'dmg', 'gz', 'jar', 'tar', 'zip'
  ]

But `touch public/foo.zip` and GETting `http://localhost:3333/public/foo.zip` also 404s

**Comment by mikemaccana** [comment]
OK `public/foo.zip` becomes `foo.zip`. Going to suggest some minor docs changes.

**Comment by brianleroux** [comment]
yea we mount `/public` at the root…this was pretty consistent feedback of 'what ppl wanted' but open to changes

**Comment by brianleroux** [comment]
Closing for now! (Don't hesitate to reopen or whatever)
