### ISSUE TITLE
General purpose abstraction to s3 bucket management

### ISSUE THREAD

**Issue by joshgillies** [arc-repos/architect#198]
After using `architect` on a few projects the last month I'd just like to say how great an experience it's been so far. Really well done to everyone involved! 🍻 

As I grow one project in particular I'm beginning to feel like there's some potential enhancements that could be made around management of application specific s3 buckets. I acknowledge that the `@static` configuration option is available, but feel like it's quite limiting.

What I'm imagining is something similar to that of `@table`, where by you define a buckets and various attributes.

For example:

```
@app
arc-s3-custom-bucket

@storage
user-uploaded-images # similar to @static this must be unique across all s3, though arc could automatically assign test/staging/production to the bucket?
  create Lambda # similar to @table the ability to assign lambdas to CRUD operations
  public false # a way to control access to objects in the bucket
```

with the above `.arc` file in mind, I'd imagine an additional `@architect/storage` helper be developed to aid in interacting with a preconfigured `AWS.S3` service based on environment.

**Comment by ryanblock** [comment]
This is interesting, would be really curious to see some detailed use cases around this. Would you mind posting some? Thanks!

**Comment by ryanblock** [comment]
While we agree with some of the use cases here, we haven't heard back on this in a while, and haven't had a lot of community demand. I think we'll likely tackle this in the future, but it doesn't seem to be a priority at the moment. Please feel free to reopen if you'd like to discuss further paths to implementation, submit a PR, or think we need to more aggressively bubble this up. Thanks for this feedback!
