### ISSUE TITLE
on profile change, deploy fails badly

### ISSUE THREAD

**Issue by remy** [arc-repos/architect#199]
**Describe the bug**

Set up a project as you would and deploy it. When the `@aws profile` is added to the `.arc` config, and deployed again the error message is harsh and unclear.

**To Reproduce**
1. Do "quick start setup"
2. Add `@aws\nprofile <other-profile>`
3. run `npx deploy`

<details><summary><strong>dump of error</strong></summary>
<pre>
Deploying 1 lambdas                                          Updating Lambdas...
deploy env-staging-get-index failed
{ ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:596019491244:function:env-staging-get-index
    at Object.extractError (/Users/remy/Sites/env/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/remy/Sites/env/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/Users/remy/Sites/env/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/remy/Sites/env/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/remy/Sites/env/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/remy/Sites/env/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Function not found: arn:aws:lambda:us-east-1:596019491244:function:env-staging-get-index',
  code: 'ResourceNotFoundException',
  time: 2018-11-19T17:03:01.563Z,
  requestId: 'f890841f-ec1c-11e8-ba7b-edea3f18d5e9',
  statusCode: 404,
  retryable: false,
  retryDelay: 99.32844406962886 }
/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:596019491244:function:env-staging-get-index
    at Object.extractError (/Users/remy/Sites/env/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/remy/Sites/env/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/Users/remy/Sites/env/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/remy/Sites/env/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/remy/Sites/env/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/remy/Sites/env/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/remy/Sites/env/node_modules/aws-sdk/lib/request.js:685:12)
</pre>
</details>
<br><br>

**Expected behavior**

Read the `ResourceNotFoundException` and present the user with description of possible problem in human text, i.e. "the lambda couldn't be updated because it couldn't be found - did you run `npx create`?"

**Desktop (please complete the following information):**
 - OS: Mac High Sierra

**Additional context**

```
                Node 8.10.0
                 npm 6.4.1
                .arc 4.3.10
```

**Comment by brianleroux** [comment]
ah yes! good one, will look into that. def can't deploy before things are created. its a bit of a tradeoff too. there's an argument to be made deploy could also create. (but then deploy would become very slow recalculating the world instead of blindly writing and assuming you already provisioned)

**Comment by remy** [comment]
I think you're right not to add create to deploy, but making errors nice'll win you friend and prizes 🏆

**Comment by filmaj** [comment]
We talked a little about this in #191, but if the goal is for arc to be idempotent, it may be needed to combine _all_ the infra-munging commands into one. Just an idea...

**Comment by brianleroux** [comment]
could see attempting to run create for the lambda if it tries to deploy and fails because it doesn't exist; we'll need to refactor to use the inventory command on deploy to button that up but super doable. that way we still have super fast deploys but if it fails it'll try to create/deploy. 🏖

**Comment by filmaj** [comment]
The way I'm imagining the idempotency to work would be kind of like ansible (not that we want to follow that yaml hell, but there are lessons to be learned): you define your infrastructure (in this case via `.arc`) and when invoked, your infrastructure is created if it doesn't exist and deployed out. As part of deployment, the existing infra is smartly inspected to see if there is a delta between what you intend to deploy vs. what you have deployed already (e.g. is there a diff between deployed lambda code vs. local lambda code, or a diff between local static assets vs. what's present in the bucket remotely).

The result being: you can run `npx deploy` (or whatever the uber-command is called) as many times as you wish, and the results will always be the same. While arc strives to do this now, in practice that's not the case because as a user you need to understand what arc does in `create` vs. `deploy` vs. `hydrate` vs. `arc inventory nuke`. Running the separate commands in a different order will yield a different result.

**Comment by brianleroux** [comment]
yeah I remember ansible…it was slow too! ;) think my suggestion fits your use case. 

npx hydrate never does anything differently no matter what order you run it in. it always works the same. nuke also. create also. deploy is the outlier here and we can fallback to slow and get the 'upsert' behavior which I think is what we want without losing the speed of the current deploys. (again this assumes we are using the `.arc` as the source of truth which I think we all agree on.)

**Comment by filmaj** [comment]
I think it all comes down to docs: if it's clear what each command does and in what order to run them then things should be 'obvious'. As a newcomer, things were not obvious to me, which is why I posed the question ;)

**Comment by brianleroux** [comment]
extremely excited about where this is leading! WIP branch w new `npx deploy` that incorporates the create fallback: https://github.com/arc-repos/architect/pull/208 and it works rather well. 

The new logic works like this:
- read inventory of lambdas based on current `.arc` file
- run prepare phase on all of them in parallel catching any failures into a singleton called retry
- filter failures from the results of the prepare phase and deploy as fast as possible (again catching any errors into the same singleton as before called retry)
- after the deploy phase is done report the result and run create on lambdas that failed by querying `retry()`

**Comment by brianleroux** [comment]
ok, shipped an updated deploy for testing: `npm i @architect/architect@rc1` to get the WIP …big thx to everyone on this thread for helping me make this workflow A+
