### ISSUE TITLE
sessions

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#201]
Architect is sessions enabled by default because the requirements for the app we were building required a secure, httponly session, and I didn't want to configure it every time I spun up a new environment. ;) The tradeoff of this is we create 2 DynamoDB tables whenever we spin up HTTP endpoints. These tables cost money and they themselves need to be manually configured read/write capacity units. We default the tables at the cheapest setting (1rcu/1wcu) which means any app getting traffic can be throttled by the session read/write. 

> NOTE: you can opt out of table creation by running with a flag: `ARC_DISABLE_SESSION=1 npx create` . You can disable session for any individual Lambda by deleting the `SESSION_TABLE_NAME` env variable from it in the console. 

## A bit more history on sessions

Web frameworks have always had database backed httponly sessions since cgi days. Recent years, the web has relaxed a bit and sessions have moved clientside and cross-origin for many use cases but primarily because its easier (no db required!) and you can then provide an authenticated/dynamic experience from  prerendered static assets talking to remote APIs. This is not necessarily insecure, however, it can be more secure. (And for systems with compliance/regulatory concerns users/developers/decision makers tend to want to err on the side of more secure!) 

More recently, JWT is trending towards recommending both httponly and to be encrypted to mitigate various xss vectors. Encrypted, signed _and_ stateless. 

## How sessions work right now in `4.x`

Currently you read/write the session using `@architect/functions` which comes bundled in the HTTP Lambda upon creation. The interface is pretty straightforward:

```javascript
let arc = reqiure('@architect/functions')

exports.handler = async function http(req) {
  // read the cookie
  let session = await arc.http.session.read(req) 
  // mutate the session
  session.count = (session.count || 0) + 1
  // write the session
  let cookie = await arc.http.session.write(session)
  // update the session cookie
  return {cookie, status: 302, location: '/'}
}
```

Under the hood `@architect/functions` uses `process.env.SESSION_TABLE_NAME` to lookup the session. If that env var doesn't exist the operations are passthru silently. (This is a debatable design choice!) 

## Stateless Proposal

If `SESSION_TABLE_NAME` equals `jwe` then store session statelessly in the cookie itself encrypted per https://tools.ietf.org/html/rfc7516#page-20 and then move this to the new default for session. Database backed sessions can become an opt in (not sure how we'd do this yet but I do think we'd want to continue support it especially now that Aurora sounds more feasible). 

Upsides
- Faster runtime in Lambda (arguable we are fatter on the wire tho)
- *Easier to get started with Architect* (you are fully in the free tier and Dynamo is now opt in)

Downsides
- Exposing more data to the client (tho encrypted, signed and httponly)
- DDB table rows can hold 400KB whereas a cookie should be well under 4KB or things will get weird

---
Would love feedback @ryanblock @filmaj @austinkelleher @kristoferjoseph

**Comment by filmaj** [comment]
I love this move!

Couple q's:

1. I have zero experience w/ building JWT frontends, let alone JWE. Do we know whether typical token size lets you slip in under the 4kb cookie max?
2. Do we care about an upgrade path for folks on DDB-backed sessions moving to JWE?

**Comment by brianleroux** [comment]
> 1. I have zero experience w/ building JWT frontends, let alone JWE. Do we know whether typical token size lets you slip in under the 4kb cookie max?

Yes absolutely, should be pretty easy to stay within that. 

> 2. Do we care about an upgrade path for folks on DDB-backed sessions moving to JWE?

I do absolutely (because I'm one of them). If we change `npx env` to allow for read/write to SESSION_TABLE_NAME the existing users can continue to use the sessions tables they already have (or set them to new ones…or set them to `jwe` and get opted into stateless sessions. There is an undocumented env var we use for signing currently `ARC_APP_SECRET` which we can also reuse for the jwe tokens. One sticking point: the minimum key size will be 16bytes to satisfy the jwe encryption requirements. 

was just playing with this here https://runkit.com/brianleroux/5bf71feaf3b51c0014e6b95a

the code for session read here is here https://github.com/arc-repos/arc-functions/blob/master/src/http/_session-read.js

and session write https://github.com/arc-repos/arc-functions/blob/master/src/http/_session-write.js

(so I think this can be totally backwards and forwards compatible without any breakage)

**Comment by filmaj** [comment]
So then upgrades would look like:

1. Set `SESSION_TABLE_NAME` to `jwe`
2. Run `npx create`
3. Run `npx deploy` (?)
4. If everything checks out, `npx inventory nuke` the old tables?

**Comment by brianleroux** [comment]
ah super interesting to see how we think about this differently 

1. they'd need to upgrade `@architect/functions` to the latest session handling by running
`npx hydrate update` and then deploy that `npx deploy`. (no need to run create unless you've added new functions)
2. `npx env staging SESSION_TABLE_NAME jwe` would opt staging lambdas into jwe
3. `npx env production SESSION_TABLE_NAME jwe` would opt production lambdas into jwe

not sure about the delete tables part…probably make that a docs problem

**Comment by filmaj** [comment]
Right, `create` wouldn't be needed. I'm still learning! 🙈and makes sense you'd need to upgrade the code, another derp on my part.

Would anything funky happen between steps 1 and 2? That is, functions are upgraded to use the new session handling code and that is deployed out, but the env var hasn't been updated yet?

100% agree that articulating the upgrade path is a docs problem. I don't feel super comfortable helping out with the code just yet but I'm happy to help out with the docs-writing part here!

**Comment by brianleroux** [comment]
As long as the session table named in SESSION_TABLE_NAME exists everything is cool. I guess when they switch all existing sessions will be invalidated which could be a bit weird but it won't fail.

**Comment by brianleroux** [comment]
ok opt in support added! fully backwards compatible. you can test it out on [staging here](https://ciayux6qbd.execute-api.us-east-1.amazonaws.com/staging/) and then check out the cookies/payloads [on production using database backed sessions here](https://hwba34x79c.execute-api.us-east-1.amazonaws.com/production/)

example source here https://github.com/brianleroux/arc-example-counter/blob/master/.arc-env

next steps would be making this the default and writing upgrade docs

**Comment by brianleroux** [comment]
for the curious: removed all smarts from session.read and session.write and made them dumb lookups for either a jwe or ddb implementations:

https://github.com/arc-repos/arc-functions/tree/master/src/http/providers

**Comment by brianleroux** [comment]
ok this is the new default! guide here https://arc.codes/guides/sessions
