### ISSUE TITLE
Support SQL!

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#203]
Looks like Aurora no longer requires a VPC so it might be fast enough to use for hot path HTTP Lambdas! This is early but think the syntax for table definition could look like this:

```
@app
oldschool

@http
get /

@sql
my-table-name
 id varchar(200)
 columnname varchar(200) 
 price float
```

How it works:
- Requires new IAM persmissions/roles
- Requires spinning up a cluster for the db =/
- Requires AWS Secret Manager for credentials
- Then, within the cluster, you create the db itself with the secrets
- And then within the db you create tables

# 🤦‍

If its fast, then we'll also want to add thinking into `@architect/data` for query logic (or bundle a new lib for talking to it if that makes more sense).

> https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "rds-data:DeleteItems",
                "rds-data:ExecuteSql",
                "rds-data:GetItems",
                "rds-data:InsertItems",
                "rds-data:UpdateItems"
            ],
            "Resource": [
                "arn:aws:rds:us-east-1:123456789012:cluster:mydbcluster",
                "arn:aws:rds:us-east-1:123456789012:cluster:mydbcluster:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:secretsmanager:us-east-1:123456789012:secret:mysecret",
                "arn:aws:secretsmanager:us-east-1:123456789012:secret:mysecret:*"
            ]
        }
    ]
}
```

**Comment by ryanblock** [comment]
We're going to let this bake for a while longer, performance of Aurora Serverless is not yet ready for serverless.

**Comment by jgallen23** [comment]
might want to check out the new data api - https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/

**Comment by andreasbhansen** [comment]
What's the status on the Aurora implementation? 🙂

**Comment by brianleroux** [comment]
Doable as a macro / otherwise still pretty slow so I wouldn't recommend unless performance isn't important
