### ISSUE TITLE
how to check lambda size?

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#206]
ive read and its been mentioned here and on the docs that lambdas be kept to 5MB or smaller.

what's the recommended way of checking this? `du -sh src/http/get-index` ? or is the gzipped size what's important? or should i deploy the code out and check on AWS directly?

thanks for any guidance!

**Comment by brianleroux** [comment]
Compressed payload of 5mb. We print out the lambda sizes every deploy:

<img width="708" alt="screen shot 2018-11-24 at 9 33 24 am" src="https://user-images.githubusercontent.com/990/48971257-10dbb080-efcc-11e8-8e5c-a9f79da27943.png">

But I also like to use DaisyDisk to investigate `node_modules`. We've made payloads a failing test in past versions of begin (tho nowadays we're well under 2mb avg lambda size with no enforcement…its more of a ppl problem than a technical one).

**Comment by filmaj** [comment]
Hah, another Fil derp 🙈 thanks for the hand-holding 👬 

Random thought: what about reporting a visual warning in the deploy output if it crosses the threshold? 

Any recommended reading about cold starts? I found [one detailed post](https://read.acloud.guru/does-coding-language-memory-or-package-size-affect-cold-starts-of-aws-lambda-a15e26d12c76).

Lemme know happy to take a stab at the reporting tweak.

**Comment by brianleroux** [comment]
it depends! if the lambda is a background task like events, queues, scheduled or table triggers who cares even. just http gets and, ideally, other verbs but not even so much then. fronted by a static website and most of the coldstart problems seem very tractable.
