### ISSUE TITLE
📗 Docs: npx create docs out of date

### ISSUE THREAD

**Issue by gauntface** [arc-repos/architect#214]
Running `npx create` results in more files than the home page mentions, it creates `public`, `shared` & `views`.

It's unclear to me if these are required directories or not but it was a shock and having a README in the `public` directory made me curious as to whether this would be published in S3 or not. 

I was looking to arc.codes for *just* functions to create a set of API's so these additional directories were a bit concerning (i.e. arc.codes isn't designed for this), but I confess this is likely an edge case and most will want static files too.

**Comment by gauntface** [comment]
Related - the generated code from npx create is *really* verbose for something just getting started. Would have preferred the minimal function that the current homepage shows.

**Comment by filmaj** [comment]
I agree with your observations here.

IMO if your arc app does not include [`@static` pragmas](https://arc.codes/guides/static-assets), then IMO `npx create` should not create a `./public` directory.

Also, for the record, deploying the static assets out via `npx deploy` _does_ upload the README to S3 as well. I think this should be filed as a separate bug (maybe). Or maybe we keep `deploy` functionality as is, to keep the sync logic simple, but definitely worth a discussion.

**Comment by brianleroux** [comment]
yea agree too! its funny the different perspectives this project draws. the static stuff in particular has been very community driven. I've kinda not really cared about that part as much and it probably shows. I think having `src/shared` all the time. I think views only makes sense if you have `@http` and `/public` only makes sense if you have `@static`. currently we have no state for create so we have no way to know if we created any of these directories already or not. so we currently will create them anytime you run `npx create` including if you have run it before and deleted those directories! thats annoying. 

my suggestion: we make this a docs problem. we no longer generate ANY of these folders and we only sync to them if they exist. 

WDYT? cc @ryanblock && @kristoferjoseph

**Comment by filmaj** [comment]
> *My suggestion: we make this a docs problem. we no longer generate ANY of these folders and we only sync to them if they exist. *

I'm not thrilled with that idea as it makes for a poorer first-time experience with the tool. What about:

1. If you include an `@http` pragma in your `.arc`, then `npx create` will create `src/`, `src/shared/` and `src/views` folders if they do not exist.
2. If you include an `@static` pragma in your `.arc`, then `npx create` will create a `public/` folder if it does not exist.
3. Mention the above in the `npx create` usage (cli help) docs
4. Mention the above in various spots on arc.codes, including:
    - the HTTP and Static Asset guides
    - the `npx create` workflow guide
    - the `@http` and `@static` `.arc.` reference guides

**Comment by brianleroux** [comment]
Can get behind these changes. It's pretty trivial to add the logic in https://github.com/arc-repos/architect/blob/master/src/create/_planner.js#L11-L15

Another thing I'm pondering, now that we have the delta fallback to `create` when a `deploy` fails maybe we want to make `npx create` to default to todays `npx create local` behavior and then have an explicit command for creating infra `npx create aws`. 

Its a big change but I think the workflow might be closer to what ppl expect coming from other project generators. WDYT?

**Comment by filmaj** [comment]
Given the structure of the current arc 'quickstart', which is all focused on running locally w/ sandbox, I like that change. I think it alleviates concerns that may give people cold feet when starting off with arc, concerns that I recall having ("whoa, this tool wants to just start blasting new infra into my AWS account!? iuno....").

Would take a scrub of the docs but that's always a good thing! I'm down to help with that.

**Comment by gauntface** [comment]
Two cents the `npx create` and `npx create aws` sounds great.

**Comment by ryanblock** [comment]
Not sure what the action items are here now. Please feel free to open some specific issues and we'll work through them. Thanks for this feedback y'all, it's super helpful!
