### ISSUE TITLE
📗 Docs: Change examples in the `shared` and `views` READMEs

### ISSUE THREAD

**Issue by gauntface** [arc-repos/architect#215]
I'm not sure what the difference is between the `shared` and `views` directories  after reading the READMEs. The example given in each README mentions `layout.js`, while the texts mentioned that the use case is different from each.

Couple of ideas:
1. Have the same example for the README's but have one file in shared and one in views and highlight why the file is in that directory
2. Reduce the README contents and link to hosted docs that explain the difference

**Comment by brianleroux** [comment]
Hey again! Sorry for the confusion. Both recent ish features. `/src/shared` is copied into ALL your lambdas (under `node_modules/@architect/shared`). The `/src/views` folder is copied to ONLY http lambdas that do `GET` requests (under `node_modules/@architect/views`. 

Main motive here is to keep the lambdas lean. View code gets heavy and (generally) you do the heavy lifting in`POST` so including all that view logic is a bummer on your payload budget when all you're going to do is a 302 redirect anyhow. 

Agree w your changes! Would also like to also add that we should only create /src/views if `@http` exists.

**Comment by brianleroux** [comment]
We've updated docs in Project Layout and removed the requirement to even have these folders. Its my feeling they cause more confusion than help and are better left discovered once code sharing is a problem rather than before.
