### ISSUE TITLE
Docs 📗: Include information on permissions

### ISSUE THREAD

**Issue by gauntface** [arc-repos/architect#216]
On my first attempt to use arc.codes (with zero to little experience with AWS), I got a host of issues around permissions that I couldn't find a clean way to fix.

Without any credentials:
> The security token included in the request is invalid.

With credentials that can access all lambda functions:
> Error: From should be a file or directory

Having a prerequisites section linked at the top of the getting started guide linking to all the setup would be helpful.

I would also live a command that either guides me through the setup OR tests my setup and calls out issues before I try to create or deploy anything. I'm imaging the test could try and deploy and remove a lambda function as a gut check that everything is working.

**Comment by filmaj** [comment]
I sort of filed this over on the arc.codes repo: https://github.com/arc-repos/arc.codes/issues/26

I _do_ have a first-stab at this guide written. I should send that PR...

**Comment by brianleroux** [comment]
Sorry about that Matt! We have assumed you are an administrator thus far but as Fil mentioned we'd like to start providing locked down roles. Given that Architect manages IAM and DNS its pretty wide open even then and we generally would assume you'd be in control of the account you want to automate.

**Comment by gauntface** [comment]
I totally have control of the account (It's my own account), but it's a brand new account and was trying to not hand over the keys to the kingdom for access keys and secret, largely because I don't 100% trust myself to keep it secure.

**Comment by ryanblock** [comment]
Unclear what our path forward is here – Amazon's permissions are gnarly, and Arc is an evolving project. If our current docs aren't sufficient, we should definitely improve that. We'd like to eventually move to a more tightly scoped trust model for our IAM roles, although doing so could result in severe consequences and frequent breaking changes, so we'll likely want to wait until things settle down more before pushing that.
