### ISSUE TITLE
default to text/html instead of application/json for generated routes

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#220]
Currently JSON has been the primary use case for API Gateway and as such it makes sense the default content type is `application/json`. This is all fine and good but if there is any error you'll see a fugly JSON error and need to view source to see the real error (in some browsers not all). The fix would be to default content type to `text/html` so errors show up in a modest easier to see format. Think this is a good change but will leave this issue open for a while to get the community temp.

**Comment by mikemaccana** [comment]
I have a little code that picks a type if none is given:

	const guessType = function(string) {
		const firstCharacter = string.trim().charAt(0);
		// Precooked JSON
		if (firstCharacter === "{") {
			return TYPES.JSON;
		}
		// HTML
		if (firstCharacter === "<") {
			return TYPES.HTML;
		}
		// Otherwise assume plaintext
		return DEFAULT_TYPE;
	};

And then:

	const makeResponse = function(body, status = "OK") {
		var type;
		if (!isString(body)) {
			type = TYPES.JSON;
			body = JSON.stringify(body, null, 2);
		}
		if (!STATUS_CODES[status]) {
			throw new Error(`Unknown HTTP status ${status}`);
		}
		return {
			status: STATUS_CODES[status],
			type: type || guessType(body),
			body
		};
	};

This means:

 - Any non-strings are encoded and sent as JSON
 - Pre-encoded JSON and HTML are sent based on checking first character

Borrow / steal ideas from it if you want.

**Comment by ryanblock** [comment]
Per Brian, going to close this!
