### ISSUE TITLE
📗 Docs: update changelog for mysterious 4.4 release! 

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#222]
Currently 4.4 is out, changelog doesn't have anything about it! 🙂

**Comment by ryanblock** [comment]
I've been kind of the sole maintainer of the changelog and this week been super heads down on Begin stuff. I gotta ask the rest of the Architect dev community to start helping me out on this!

**Comment by brianleroux** [comment]
yeah this is on me too sorry mike (and ryan)! fil added s3 delta deploys 

https://github.com/arc-repos/architect/commit/5f45293c264967edcb27ff4437f8040a2b0b4726

and a bit before that we tweaked `npx deploy` to now also fallback to `create` on any routes that failed. so now you can just edit the `.arc` and run `npx deploy` immediately. 

have more deploy enhancements planned! eg. we could now just use layers for /shared and /views probably making deployment even faster. (=

**Comment by ryanblock** [comment]
Thanks for asking! Here's how I've done our changelog:
- Generally follows [Keep A Changelog guidelines](https://keepachangelog.com/en/1.0.0/) format
- Entries are condensed by day (i.e. if multiple versions are released on one day, list all changes under the highest version from that day)
- Releases separated by 2 returns + 1 rule (`---`)
- Sections within releases separated by 3 returns
- Generally have not maintained an `Unreleased` section, but doesn't mean we can't do that in the future

Haven't really maintained any other release rituals that I can think of off the top of my head.

Re. CD, can def imagine releases publishing automatically with git tags, wouldn't be too difficult to get that set up – will defer to @brianleroux to make the call on if/when we do something like that, tho.

**Comment by ryanblock** [comment]
Finally got to it today! https://github.com/arc-repos/architect/commit/0f8c1391c9908b25ecddb1683917b0913d8a5e12

Also added to [PR template](https://github.com/arc-repos/architect/commit/41b53a007dd998b921212aaf8b89be27067ed632), help maintaining this is much obliged!

**Comment by mikemaccana** [comment]
Thanks Ryan! 🙂
