### ISSUE TITLE
add role to .arc-config

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#224]
we currently have the ability to define per route roles OR globally fallback to a default `arc-role`. its worked great! continues to. a nice enhancement would be to add named roles to `.arc-config` so you can opt multiple lambdas into a role without having to repeat role.json in a whole bunch of different lambdas. this strikes a nicer balance for least privilege and centralizing access control config.

example

```
@aws
timeout 30
role my-custom-role
```

these leaves defining my-custom-role would be an exercise left to the developer but we could further enhance by adding a magical `src/roles` folder for capturing the role config in code.

**Comment by ryanblock** [comment]
Closing for now, hasn't come up and we support this another way in [`roles.json`](https://arc.codes/guides/iam).
