### ISSUE TITLE
Sandbox: lambdas that don't exit timeout

### ISSUE THREAD

**Issue by grncdr** [arc-repos/architect#227]
When a lambda function starts an interval, timeout, or anything else that prevents a node process from exiting, sandbox requests will timeout.

### minimal reproduction

```js
export.handler = async function http() {
  setTimeout(() => {}, 5000)
  return {body: 'ok'}
}
```

Even though the above handler completes immediately, the sandbox won't see the result until the process exits after 5 seconds, at which point it's already timed out.

### real-world use case

I want to use Aurora Serverless from my lambdas with `mysql.createPool`. This is totally fine to use on AWS, and can give some performance benefit, but in the sandbox every request that uses the DB will timeout due to the pool keeping connections alive.

### how to fix (maybe)

Maybe sandbox/http/invoke-lambda could eagerly detect the `__ARC__ {...}` output line and kill the process as soon as it's parsed a result?

**Comment by ryanblock** [comment]
Was thinking about this one.

I recently added `SANDBOX_TIMEOUT` (in seconds) env var to grant the sandbox more time where appropriate, and individual functions' [`.arc-config`](https://arc.codes/reference/arc-config)s are respected, so they won't exit too early on you.

Maybe not as elegant as what you're proposing, but perhaps it'll get the job done?

**Comment by grncdr** [comment]
Change `setTimeout` to `setInterval` to get a better sense of the problem. The sandbox\* waits for the entire Node (or Python etc.) process to exit before it considers the invocation complete, so anything that keeps the process alive indefinitely (think connection pools) is going to exceed any timeout value you define.

<small>\* as of when I wrote this, I haven't reviewed the latest changes</small>

**Comment by ryanblock** [comment]
Closing in favor of these issues, for which I believe fixes are under active development by @mikemaccana:
- https://github.com/arc-repos/architect/issues/355
- https://github.com/arc-repos/architect/issues/358
