### ISSUE TITLE
proposal: support custom runtime layer

### ISSUE THREAD

**Issue by knksmith57** [arc-repos/architect#234]
Lambda now supports custom runtimes. [Announcement here](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-now-supports-custom-runtimes-and-layers/).

A number of companies / projects are releasing modified node.js runtimes, including [N|Solid for AWS Lambda](https://docs.nodesource.com/nsolid_aws_lambda/docs) by NodeSource.

Custom runtimes can provide things like enhanced security, batteries-included monitoring, and custom node.js versions not-yet available from lambda directly.

**Comment by brianleroux** [comment]
Like it! We're investigating for sure. Has negative performance implications but being runtime agnostic is def on our roadmap. We also see layers as a way to speed up deployments of /shared folder. You can track the progress here! https://github.com/arc-repos/architect/issues/183

(I expect to return to this in the coming weeks but any assistance is super appreciated!)

**Comment by ryanblock** [comment]
Layers support be released this week as Arc `5.7`!
