### ISSUE TITLE
'npx deploy' no longer shows URL after deploying

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#235]
**Describe the bug**

`npx deploy` no longer seems to be showing a URL to visit after deploying, eg: per the docs https://arc.codes/reference/arc-deploy I'd expect:

```
    Success! Deployed 1 Lambdas in 2.042s 
    -------------------------------------
    src/html/get-index ... testapp1-production-get-index ... 0.15 mb
    https://yds7hyimua.execute-api.us-east-1.amazonaws.com/production                            
```
However recent `npx deploy`s don't have a URL after `Success`. `create` will show a URL, but `deploy` won't - this is easily replicable using the testapp from https://arc.codes/quickstart/install

```
    ~\OneDrive\Documents\myapp\testapp $ npx deploy
            app ~ testapp
        region ~ us-west-2
        profile ~ xxx

    √ Success! Deployed 1 Lambdas in 19.729s

    src\http\get-index ... testapp-production-get-index ... 0.19 mb
    ~\OneDrive\Documents\myapp\testapp $

```
 
**To Reproduce**
`npx deploy` on arc 4.4.5 seems to trigger the issue. But also: **Is there a seperate command to see the production / staging locations?**

**Expected behavior**
See the URL

**Desktop (please complete the following information):**
 - Windows 10, arc 4.4.5

**Comment by ryanblock** [comment]
Is this still an issue? I tried to reproduce and wasn't able to. (Results below.)

Please try testing with both `@domain` specified and not, if possible.

Right now there isn't a separate command to get production/staging URLs, but here's the code that handles that: https://github.com/arc-repos/architect/blob/master/src/deploy/helpers/get-url.js#L12-L42

Thanks!

--- 

With `@domain` specified:
```
[15:00:59] (╯ಠ益ಠ)╯︵~/test npx deploy
        app ⌁ ryanblock
     region ⌁ us-west-1
    profile ⌁ personal
    version ⌁ 4.4.9

✓ Success! Deployed 3 Lambdas in 44.606s

src/http/get-index ........ ryanblock-staging-get-index ........ 0.54 mb
src/http/get-robots_txt ... ryanblock-staging-get-robots_txt ... 0.54 mb
src/http/get-000page ...... ryanblock-staging-get-000page ...... 0.54 mb

https://staging.ryanblock.com
```

No `@domain` specified:
```
[15:01:46] (╯ಠ益ಠ)╯︵~/test npx deploy src/http/get-index/
        app ⌁ ryanblock
     region ⌁ us-west-1
    profile ⌁ personal
    version ⌁ 4.4.9

src/http/get-index/ ... ryanblock-staging-get-index ... 0.54 mb

https://xxx.execute-api.us-west-1.amazonaws.com/staging
```

**Comment by filmaj** [comment]
I'm using 4.4.11 and also cannot reproduce.

**Comment by mikemaccana** [comment]
Sorry about the wait here, I was away over Christmas. I can't reproduce on 4.4.12, everything now good here. 👍

**Comment by mikemaccana** [comment]
Huh looks like I spoke too soon. Brand new project:

```
~\Documents\new-test-app $ npx deploy
        app ~ testapp
     region ~ us-east-1
    profile ~ default
    version ~ 4.4.12

 √ Success! Deployed 1 Lambdas in 10.789s

src\http\get-index ... testapp-staging-get-index ... 0.19 mb
```

**Comment by mikemaccana** [comment]
Same thing - continually finishes on the line above. I'm on Windows if
that's relevant, I can test on a Linux VM tomorrow though.

**Comment by ryanblock** [comment]
Hmm, I think perhaps it may be. Here's my first deploy with a new app that didn't exist:

**Comment by ryanblock** [comment]
Hmm, I think perhaps it may be. Here's my first deploy with a new app that didn't exist:
```
(╯ಠ益ಠ)╯︵~/git/arc-test-projects/index-only npx deploy
        app ⌁ testapp
     region ⌁ us-west-1
    profile ⌁ personal
    version ⌁ 4.4.12

src/http/get-index ... testapp-staging-get-index ... Creating


✓ AWS resources created
https://foo.execute-api.us-west-1.amazonaws.com/staging
https://bar.execute-api.us-west-1.amazonaws.com/production
```
Then a subsequent deploy:
```
(╯ಠ益ಠ)╯︵~/git/arc-test-projects/index-only npx deploy
        app ⌁ testapp
     region ⌁ us-west-1
    profile ⌁ personal
    version ⌁ 4.4.12

✓ Success! Deployed 1 Lambdas in 13.341s

src/http/get-index ... testapp-staging-get-index ... 0.19 mb

https://foo.execute-api.us-west-1.amazonaws.com/staging
```

**Comment by ryanblock** [comment]
Weird, but glad it isn’t reproducing.

Ps ‘npx inventory --nuke’
