### ISSUE TITLE
Editor artifacts get copied over into lambda `node_modules/@architect/shared`

### ISSUE THREAD

**Issue by filmaj** [arc-repos/architect#252]
**Describe the bug**
So I'm working on e.g. `src/shared/views/layout.js` in vim, and thus a `.swp` file is created as part of that. If I then run `npx sandbox` in a separate shell, the `.swp` file will get copied to all of my lambda's `node_modules/@architect/shared` folders.

Would be nice if it didn't do that but maybe this is my problem and not arc's.

arc v4.4.12

**Comment by joshgillies** [comment]
Sounds similar in scope to this issue: https://github.com/arc-repos/architect/issues/247.

**Comment by brianleroux** [comment]
recommend `set noswapfile` in your `.vimrc` 💃 

https://github.com/brianleroux/quick-vim/blob/master/vimrc#L8
