### ISSUE TITLE
Discuss: deprecate old 'workflows' package?

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#256]
Depends on whether you want arc 3 user to update or not, but this could help users know about the package rename:

     npm deprecate @architect/workflows@"< 4.0.0" "This package is now called @architect/architect - please remove @architect/workflows and use the latest @architect/architect"

Or whatever you prefer.

**Comment by ryanblock** [comment]
👀 https://www.npmjs.com/package/@architect/workflows

**Comment by brianleroux** [comment]
🔥🔥🔥
