### ISSUE TITLE
Cannot reproduce `TypeError: Cannot read property 'id' of undefined` error

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#260]
**Describe the bug**
Earlier today we saw a couple of folks get this error after a bad build of Architect went out:
```
TypeError: Cannot read property 'id' of undefined
    at _createResources (/path/to/proj/node_modules/@architect/architect/src/create/aws/_create-route/_create-resource/_maybe-create-resources/index.js:19:23)
    at Response.each (/path/to/proj/node_modules/run-waterfall/index.js:21:22)
    at Request.<anonymous> (/path/to/proj/node_modules/aws-sdk/lib/request.js:364:18)
``` 

This error in `src/create/aws/_create-route/_create-resource/_maybe-create-resources/index.js:` at 19:23 means the resource creation planner attempted to create an `@http` endpoint, and during execution, the event that creates an http route in API gateway can't find the API that it's supposed to create the resource in.

The primary issues in the build were reproduced and patched; however, even before the patch, this issue has been surprisingly hard to reproduce. (I've subsequently tried to reproduce running the bad build without luck.)

A normal resource creation plan (in pseudocode) looks something like this:

1. create iam roles
2. create function code
3. create lambda
4. [maybe some steps for tables if you have any]
5. create api gateway
6. create http route
7. create api gateway deployment

Each step along the way skips itself if it detects the action it's trying to take has already been accomplished (i.e. if the Lambda already exists just `callback()` instead of executing a Lambda creation), so you'd get this error if you ran step 6 before step 5 runs or completes, and only on a project that hadn't yet been created or deployed to.

Architect resource creation plans are generated deterministically, which means this error (as I currently understand it, anyhow) was likely either:
- An ephemeral and/or esoteric API gateway API issue (e.g. your API was created, yet somehow not returned in the list of your account's available APIs; or some AWS error state marks a valid API as invalid, keeping it from being returned in the list of your account's available APIs; eventual consistency issues in responses to `aws-sdk` calls, etc.)
- The result of an out of order execution, which would imply some kind of throttle error, or a condition  that results in the execution of a code path that short circuits the plan order
- Possibly something else I'm not thinking of?

Unfortunately, after nearly 3 dozen project creations, I have been unsuccessful at reproducing this issue, and the two folks who had it (@brianleroux and @alexdilley) haven't reproduced, either.

So I'm opening this issue here to see if anyone can post repro steps, or at very least the `.arc` + environment information of the project that's resulted in this error.

🌈🌈🌈

**Comment by alexdilley** [comment]
Have executed a few scenarios but have been unsuccessful in replicating. Will keep conscious of it 👀

**Comment by ryanblock** [comment]
Per Brian, this could also be related to API resource creation rate limiting, not just API creation as I mentioned above. So that would make sense to me as to why it's so difficult to reproduce. Still, will leave this open.

**Comment by brianleroux** [comment]
lgtm!
