### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by asunar** [arc-repos/architect#262]
**Describe the bug**
Trying out the [Serverless frontend patterns with Architect Views](https://blog.begin.com/serverless-front-end-patterns-with-architect-views-cf4748aa1ec7)

**To Reproduce**
1. Follow the steps on [Serverless frontend patterns with Architect Views](https://blog.begin.com/serverless-front-end-patterns-with-architect-views-cf4748aa1ec7) until `npx create --local`

**Expected behavior**
arc-views
├── public/
├── src
│   ├── http
│   │   └── get-index/
│   ├── shared/
│   └── views/
└── .arc

**Actual behavior**
No public, shared or views directories are generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/204049/51071181-70405f00-1612-11e9-8843-b9bda29c7117.png)

**Desktop (please complete the following information):**
 - OS: win 10

**Additional context**
Are the instructions on this blog post out of date?

**Comment by ryanblock** [comment]
Apologies, out of date docs! You must now opt into those folders by creating them yourself. Can you make this issue to update docs? Will do tomorrow. Thanks!

**Comment by asunar** [comment]
Updated title though not sure if that's what you meant. I don't think I have access to apply labels.

**Comment by ryanblock** [comment]
Yeah that's all I meant. Updated those blog posts, will continue to update our docs and close this out. Thanks for that, sorry for the rough edges you caught there!

**Comment by ryanblock** [comment]
Seems like this is resolved!
