### ISSUE TITLE
CORS enabled by default

### ISSUE THREAD

**Issue by alexdilley** [arc-repos/architect#283]
**Describe the bug**
`Access-Control-Allow-Origin: *` header set in responses by default.

**To Reproduce**
1. Follow [instructions](https://arc.codes/quickstart/install) to create a new arc project with a `get /` endpoint.
2. Set handler code to:
```js
exports.handler = async function http(request) {
  return {
    body: JSON.stringify({message: 'hello, world!'}),
    // cors: false,
  };
};
```
3. Deploy and hit endpoint via `curl -v`.
4. Note response headers.

**Expected behavior**
`Access-Control-Allow-Origin` response header to not be set; should be set only when `cors: true`.

**Screenshots**
```
...
< Access-Control-Allow-Origin: *
...
```

(If the `cors: false` property is uncommented then the header isn't set.)

`v5.0.6`

**Comment by ryanblock** [comment]
Looks like we've since resolved this, closing issue but please let us know if I'm missing something here!
