### ISSUE TITLE
How to test @scheduled functions?

### ISSUE THREAD

**Issue by schpet** [arc-repos/architect#291]
hi!

what's a good way to test or run a scheduled function locally? 

my scheduled function uses some env vars so my tests currently load up their own env vars:

```js
let test = require("tape")
let join = require("path").join
let parse = require("@architect/parser")
let read = require("fs").readFileSync

// load env vars, copied from:
// node_modules/@architect/architect/src/util/populate-env.js
let envPath = join(process.cwd(), ".arc-env")
let raw = read(envPath).toString()
let env = parse(raw)
env[process.env.NODE_ENV].forEach(tuple => {
  process.env[tuple[0]] = tuple[1]
})
...
```

and do not call the `exports.handler = arc.scheduled(handler)` function directly.

appreciate how easy arc made deploying my first lambda function, thanks for the work on this!

**Comment by brianleroux** [comment]
its pretty easy to mock out the scheduled payload so you can just invoke locally yourself

```javascript
let myfn = require('../src/scheduled/my-timer/index.js')
let test = require('tape')

test('myfn', t=> {
  t.plan(1)
  let event = {}
  let context = {}
  myfn(event, context, function done(err, result) {
    t.ok(true, 'executed function')
  })
})
```

(didn't test but try that out and lmk how it goes!)

**Comment by schpet** [comment]
that is easy, and solves it, thank you!
