### ISSUE TITLE
Events, scheduled, queues default timeout to 15 minute

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#293]
Right now all Lambdas are provisioned with 5s timeouts. This makes sense for a web hot paths, but can lead to backgrounded events timing out early.

Events, scheduled, and queues should assume the natural ceiling afforded to non hot path / background tasks, which on Lambda right now is 15 minutes.

This issue has bitten us a couple times in real life, so I'm filing this as a bug.

**Comment by brianleroux** [comment]
Thought about this some more and feeling it is better to have a default of 5s and allow for opt in (as it is today) than creating a rules table which ppl also have to memorize or lookup.
