### ISSUE TITLE
proxy.public requires options object with spa set

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#299]
**Describe the bug**
The `@architect/functions` `proxy.public` method requires a parameter object containing an `spa` boolean in order to function. It should default to `spa: false` and not require options to be set.

**To Reproduce**
1. Set up a project in Arc 5.5
2. Add this to `src/http/get-index/index.js
```
let arc = require('@architect/functions')

exports.handler = arc.proxy.public()
```
3. Responses will fail

**Expected behavior**
Should be able to use `proxy.public()` without `{spa:false}`

**Comment by brianleroux** [comment]
(fixed!)
