### ISSUE TITLE
`npx logs nuke` doesn’t delete all logs

### ISSUE THREAD

**Issue by mikeal** [arc-repos/architect#311]
**Describe the bug**

The `aws-sdk` function for listing log streams truncates the number of log files when there are many logs. This means that `npm logs nuke` only ends up removing a portion of the logs. I had hundreds of log files so it seemed like it just wasn’t doing anything.

**To Reproduce**
1. Deploy an app and log **way** too much shit.
2. With the aws cli do `aws logs describe-log-streams` and very you have more log streams than anyone should have.
3. Run `npx logs nuke`.
4. List the streams again.

**Comment by ryanblock** [comment]
> `Deploy an app and log **way** too much shit.`

<img src="https://media.giphy.com/media/3o6vXQ1IrmD6Gezb5m/giphy.gif" width=300>
