### ISSUE TITLE
WebSockets broken in sandbox for ^5.5.0

### ISSUE THREAD

**Issue by rschweizer** [arc-repos/architect#328]
**Describe the bug**
The [HTTP fallback to get-index](https://github.com/arc-repos/architect/blob/747e8980813e54bc07e7d7db9279df22c41d7dcf/src/sandbox/http/fallback.js#L14-L53) introduced with commit https://github.com/arc-repos/architect/commit/747e8980813e54bc07e7d7db9279df22c41d7dcf in v5.5.0 breaks web socket support in the sandbox.

**To Reproduce**
1. Clone `https://github.com/arc-repos/arc-example-ws`.
2. Update `@architect/architect` in `package.json` from `^5.0.7` to `5.5.0` and install.
3. Run `npx sandbox` and visit `http://localhost:3333`.
4. Type something into the input and press enter.
5. Check the network tab in the inspector of your browser and verify that the message was sent using the web socket connection but the expected response was not received.

**Expected behavior**
To receive the expected response message via web socket.

**Additional context**
Adding another `else if (req.originalUrl === '/__arc') next()` after [line 16](https://github.com/arc-repos/architect/blob/747e8980813e54bc07e7d7db9279df22c41d7dcf/src/sandbox/http/fallback.js#L16) fixes the problem, so I assume the logic below line 16 might overwrite some sort of routing logic used for the local web socket functionality. Haven't dived any deeper into the code yet, but would this make sense?

**I'd be happy to help and contribute!**

**Comment by ryanblock** [comment]
Gnarly, thanks for reporting! Will defer to @brianleroux since he wrote that code – he should be back from vacation tomorrow.

**Comment by rschweizer** [comment]
Thanks @ryanblock! Let me know if I can help, @brianleroux. If you can fill me in on the details, how exactly this function should behave, I'd be happy to open a PR to fix it.

**Comment by mikemaccana** [comment]
Possibly related to https://github.com/arc-repos/architect/issues/312

**Comment by ryanblock** [comment]
Sorry, we've been a bit backed up due to some other large-delta work we've been on, I'll prioritize this for today!

**Comment by ryanblock** [comment]
Released in 5.6.2!
