### ISSUE TITLE
RFC: Cache-control headers

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#332]
I've been working on PRs for [Architect](https://github.com/arc-repos/architect/pull/325) + [Architect Functions](https://github.com/arc-repos/arc-functions/pull/28) that enable `cache-control` headers¹ for responses.

## Background

This stuff is annoying and dry but painfully necessary. I took it for granted, even, and recently we got burned by it when a rural ISP invisible proxy-cached some index.html responses because we did not set anti-caching headers. (And hey, shame on us for allowing that to happen!)

I find implementation of client (and proxy) facing caching headers is easiest to reason about by bucketing response content in two categories: core document responses (HTML, JSON), and all other assets (JS, CSS, images, fonts, manifests, whatever else).

Generally speaking, we want our core document responses to remain uncached, and depending on our needs, have various caching directives for everything else.

## Summary of changes
- All responses (dep free, AF, AF proxy) will now support a customizable `cacheControl` key (or in the case of [AF proxy]((https://arc.codes/reference/proxy-public)), config setting)
- If `cacheControl` is not provided in your responses, the defaults are:
  - HTML and JSON
    - `cache-control: no-cache, no-store, must-revalidate`
    - Alternate, even more aggressive version, presented for discussion: `cache-control: no-cache, no-store, must-revalidate, max-age=0, s-maxage=0`
  - Anything that's NOT HTML and JSON
    - `cache-control: max-age=86400` (i.e. everything will get cached for 1 day, unless otherwise specified)
- Files delivered by AF proxy will support `if-none-match` / `ETag` out of the box, and will deliver `304`s as necessary

### Example
```js
exports.handler = () => {
  return {
    cacheControl: 'max-age=60',
    body: 'this message will self destruct in 60 seconds'
  }
}
```

## Questions
- Thoughts on whether to be turbo super aggressive with the HTML / JSON anti-caching directives? Or other directives / approaches you'd like to see?
- Anyone feel XML be included with HTML and JSON in default anti-caching directives?
- Feelings or concerns about defaulting to `max-age=86400` for non-HTML/JSON? (This is still better than nothing, because invisible caches may cache for even longer than 1 day without any headers.)
- What am I missing?

## Followups
- If there's desire / demand, we can add `if-none-match` / `ETag` support outside of proxy, but because it requires some introspection of the body, it would likely be confined just Architect Functions for now

---

¹ Why `cache-control` and not `expires`, etc.? `cache-control` is the spec standard for this since http 1.1 (i.e. 20+ years), and having a single way to control caching (already super complicated) is more deterministic.

**Comment by alexdilley** [comment]
It's quite common to set the cache expiry a year ahead since immutable assets should in reality never expire, and a year seems – conventionally – to be the value long enough in the future to be considered "never". (Object names are typically a fingerprint to achieve this static nature.) Why a day – if it's a concern that an asset may need to be revalidated then any value is arguably wrong?

What I see most often:

```
Cache-Control: public, max-age=31536000, immutable
```

I'm still of the opinion that the `static` path could – as a framework convention – represent "all assets what never expire". I appreciate the desire to make it configurable – not everyone employs a hashing strategy – but mutable assets can easily just be located elsewhere.

(I'm sure you're aware(!) but in the case of HTTP proxies to S3 – aka paths under `/_static` – then caching behaviour is applied when copying files to S3.)

**Comment by ryanblock** [comment]
Totally, and I considered this. I weighed that pattern (which makes total sense as a best practice) against the dangers inherent of setting a new default. The goal is, as always, to make improvements while minimizing impact or possibility of breakage.

So, would I be upset if all of a sudden external, invisible-to-me proxies started aggressively caching my responses for 1 year without my prior knowledge and opting-in? Probably.

In other words, is it safe to always assume fingerprinting? Sadly, although everything should be doing it, I don't think it can be assumed – thus, it seems the conservative (but still adequate) approach would be to not assume it. Hence my hedge on that being to reduce `max-age` from 1 year (or greater) to 1 day – enough to keep the edge and client caches warm while hopefully keeping you out of trouble. Then, when you're ready to fingerprint, crank it up.

Thoughts?

(And yes, thanks for the reminder about setting cache-control headers in S3 / `_static`, that is indeed another dimension I've been working on, and will tackle as we lock this down.)

**Comment by alexdilley** [comment]
Yus. Rugs pulled, feet under, etc.

The day vs year age thing, I'm not sure. Having users wait up to a day with a potentially stale resource? Damage limitation, I guess. Or do you simply make it binary: immutable (cached) vs not.

(There is a partially-supported cache control extension to the effect I'm suggesting fwiw: http://bitsup.blogspot.com/2016/05/cache-control-immutable.html.)

**Comment by ryanblock** [comment]
Setting `immutable` effectively disables revalidation, yes? So that's a nice characteristic to pair with `max-age`, but if you're suggesting using that as an alternative to setting a `max-age`, I'm not so sure – is that what you're suggesting?

**Comment by alexdilley** [comment]
No, to pair. I was just highlighting that there's already a term floating around that governs [one of] the kinds of pattern you're aiming to achieve. My question: do you want to support caching ages in between `immutable` and `must-revalidate`?

**Comment by ryanblock** [comment]
Yeah, I think we could def pair `max-age` with `immutable`. Based on our offline conversation, I think the second question you're asking is trying to get at whether we want to enable full `cache-control` customization, and I believe the answer is yes (for now!), not unlike how we support full `content-type` customization.

**Comment by ryanblock** [comment]
Initial release of this went out today in Arc `5.5.9` and Arc Functions `2.0.15`. Leaving this open for active input and discussion a bit longer, we can always make changes.
