### ISSUE TITLE
Wildcard subdomain?

### ISSUE THREAD

**Issue by mikeal** [arc-repos/architect#336]
I can't quite figure out how to have a wildcard domain that points to my index lambda.

The default instructions for setting up a custom domain seem to actually ad a wildcard handler but I don't see any way to actually configure it to point any kind of pattern at my lambda function.

Any help or pointers would be appreciated :)

**Comment by ryanblock** [comment]
Hmm, great question, never tried this. Are we even sure APIG has wildcard support? https://forums.aws.amazon.com/thread.jspa?threadID=229983

**Comment by mikeal** [comment]
Looks like they do but the config is a little particular
https://stackoverflow.com/questions/51291166/aws-route-53-wildcard-subdomain-with-api-gateway/51619262

**Comment by ryanblock** [comment]
Maybe I'm missing something, but that answer says:
> EDIT: Unfortunately AWS API Gateway does not support wild-card subdomain name as we can see in the first point of this link: Api Gateway Known Issues

Links to: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html
Item one: `API Gateway does not support wildcard subdomain names (of the *.domain form). However, it does support wildcard certificates (certificates for wildcard subdomain names).`

**Comment by mikeal** [comment]
Bah, I should have finished reading that.

This is very unfortunate.

**Comment by ryanblock** [comment]
Word, gonna close but happy to keep chatting, this is an interesting scenario!

In your case, is the use case: "I want to respond from any subdomain someone may enter" or "I don't want to set up DNS entries for every subdomain I want to use"?

Because if you know all the subdomains you want to use, you may still be able to accomplish this with a wildcard in DNS and known (manually configured) domain mappings in APIG.

**Comment by mikeal** [comment]
It's "I need to respond to any subdomain request."

Long story short, I have a block based file system abstraction that is
content addressed. So I would like to have {hash}.domain.com serve the
filesystem for that hash (pulled as blocks from S3 and turned back into
files).

If I were to add a subdomain for each hash, what kind of limits might I see
on APIG? The set is easily thousands and potentially millions.

**Comment by ryanblock** [comment]
Ah, in that case I’d strongly advise against, there are always limits, but more importantly they just take a while to provision up.

What’s wrong with get /:hash ?

**Comment by mikeal** [comment]
There's a security concern serving them from the same domain. We do it in
another project and there's a lot of extra work that goes into resolving
the security issues.

**Comment by ryanblock** [comment]
I could imagine setting up a reverse proxy to transform subdomain requests into path-based requests for APIG, like:
client → `{hash}.foo.com` → [some simple reverse proxy] → APIG `get /:hash` → Lambda

Of course, that reverse proxy is out of the scope of Arc right now, but it shouldn't be too hard.
