### ISSUE TITLE
Unable to create a single @http endpoint without getting throttled by AWS

### ISSUE THREAD

**Issue by roxeteer** [arc-repos/architect#343]
**Describe the bug**
Using Architect 5.5.10, I'm trying to create the initial setup for my app. I'm unable to get a proper setup without the process being interrupted by AWS throttling.

Here's my full `.arc` file. The `get /` is using the Hello World code created by `npx create local`.

```@app
myapp

@aws
region eu-north-1
profile default

@http
get /
```

This is what I'm getting every time, even after multiple retries:

```bash
$ npx create
        app ⌁ myapp
     region ⌁ eu-north-1
    profile ⌁ default
    version ⌁ 5.5.10

∙●∙ Create: skipping @http myapp-production-get-index, already exists
-----
Error Too Many Requests
-----
Congratulations: you have been throttled! This is a very common error with AWS and nothing to worry about. This means you are working faster than your account is currently provisioned to handle. Try re-running npx create after a few minutes. If the problem persists you can request limit increases by contacting AWS support.
```

I've now asked for AWS to increase the rate limit, but I'm not sure if I can expect them to do so without knowing why Architect is hitting the limit.

**Expected behavior**
The `npx create` process shouldn't make so many requests it gets throttled in the most simple imaginable setup.

**Comment by ryanblock** [comment]
Hey @roxeteer, that sounds pretty unusual, like perhaps something is not right at `eu-north-1`. Can you try a different AZ?

**Comment by roxeteer** [comment]
I managed to create the initial setup on `eu-central-1`. It took well over 2 minutes, but worked in the end anyway.

Close this issue if you think it's solely an Amazon issue.

**Comment by ryanblock** [comment]
About 2 mins to provision sounds about right, but rate limiting is still pretty uncommon. Let me know if you hit any more snags!

**Comment by roxeteer** [comment]
@ryanblock Received a reply from AWS support. As I predicted, they were not willing to increase the rate limit. I told them I wasn't able to get my Lambda provisioned on eu-north-1, but that it worked on eu-central-1. 

> I am glad you got it up and running at least, even if not in the ideal region.
> 
> I checked to see if there are any known issues with Stockholm and found no reports of anything malfunctioning.
> 
> The only thing I have left to suggest is to start completely over again there and see if that works.
> 
> The complexity of your question is a bit outside the billing and accounts level that comes with our Basic support and will probably need to be answered by our Premium Support team. I want to make sure you still get the help you need, so I’m happy to provide you with additional resources that I think may be helpful.

They continued with links to the documentation and with the suggestion that I post my question to the AWS Forums and see if someone there is able to help.

**Comment by ryanblock** [comment]
I'm sure it's not very satisfying to hear, but there is a great degree of variability in AWS regions in terms of features, speed, and even reliability of some services, and that seems like the likely culprit here.

Of course, we'd like for you to be able to provision in the region of your choosing! I think we are going to be making some improvements in this area in the coming weeks related to some other feature work, but in the mean time I'd be curious to know what happens if you tried at `eu-north-1` again.

**Comment by roxeteer** [comment]
It's still failing, although I tried with my actual setup which contains also another `@http` endpoint in addition to `get /`. But that really shouldn't be too much for AWS to handle 😂
