### ISSUE TITLE
How can I specify "context.callbackWaitsForEmptyEventLoop = false" for low latency DocDB / Mongo calls ?

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#346]
**Describe the bug**

If `context.callbackWaitsForEmptyEventLoop = false` is specified, a DB connection can be maintained in a global variable in the lambda's container, resulting in connection times of 100ms vs 500ms. See https://www.mongodb.com/blog/post/serverless-development-with-nodejs-aws-lambda-mongodb-atlas, but this also applies to AWS DocumentDB.

Can I specify this with Architect today? If not it would be useful to specify it in future.

**Comment by brianleroux** [comment]
you can do that today! `context` is the second argument to dep free functions =)

example: https://earth-4gq-staging.begin.app
source: https://github.com/brianleroux/test-context/blob/master/src/http/get-index/index.js

**Comment by mikemaccana** [comment]
So can I just:

    exports.handler = async function http(request, context) {
      // See https://www.mongodb.com/blog/post/serverless-development-with-nodejs-aws-lambda-mongodb-atlas
      context.callbackWaitsForEmptyEventLoop = false
      ...
    }

And it'll work exactly like https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html says? 

I can update the docs and middleware - https://arc.codes/guides/http just mentions the request, I may need to work on middleware so it it provides access to context too - in my own case a lot of my routes will be accessing data and warm DB's are useful, that should be a pretty common scenario.

**Comment by brianleroux** [comment]
yessir, sgtm!

**Comment by mikemaccana** [comment]
What I don't understand is: how will changes to `context` end up back in the (lambda) handler? Since I'm just returning a `response` JS Object and not doing anything with the modified `context`?

**Comment by brianleroux** [comment]
my impression is this means the microvm gets recycled quicker? IDK! we use Dynamo 🤷‍♂️

**Comment by mikemaccana** [comment]
I get the part about the MicroVM (and can document it), but what I don't get is how changes to `context` actually get passed from our `async` function back to AWS. Like I could do `context.banana = true` and since my async function isn't returning `context` somewhere or doing anything else with it, does AWS Lambda really see it?

**Comment by mikemaccana** [comment]
That's a generic/raw Lambda question though, so I'll do some investigation and ask it on StackOverflow later if needed. Nevermind!

**Comment by brianleroux** [comment]
ya I'm totally curious too; the docs are pretty thin!

**Comment by mikemaccana** [comment]
Well it definitely works, I've tested it, see answer here (kinda talking to myself but if you're interested): https://stackoverflow.com/questions/45705770/sharing-db-connection-across-aws-lambda-function-calls/55569742#55569742

**Comment by mikemaccana** [comment]
[Asked AWS on Twitter](https://twitter.com/mikemaccana/status/1115201091925368832?s=20), hope they send a response

**Comment by ryanblock** [comment]
Looks like we're good here for now, I think! Please reopen if appropriate.
