### ISSUE TITLE
Elect / Nominate representative(s) to the OpenJS Foundation CPC

### ISSUE THREAD

**Issue by jorydotcom** [arc-repos/architect#349]
## Context
As part of the new [OpenJS Foundation's bylaws](https://github.com/openjs-foundation/bootstrap/blob/master/artifacts/OpenJS-Foundation-Initial-Merged-Bylaws.pdf), the Cross Project Council (CPC) has been [chartered](https://github.com/openjs-foundation/bootstrap/tree/master/proposals/stage-2/CPC_CHARTER) to serve as the primary governing body for programs and regular support of Foundation projects. For example, it will be responsible for things like infrastructure, travel assistance, CoC support, accepting new projects into the foundation, and mentorship programs to name a few. It will also be responsible for electing board representative(s) to the OpenJS Foundation board of directors.

**Any interested person from our project communities can attend CPC meetings and volunteer to participate in tasks.** For most programs, the CPC is expected to operate on the consensus of OpenJS Foundation project members. Issues that require a vote - namely the election of Board representatives and accepting a new project - will be memorialized by a voting CPC membership comprised of up to 2 representatives from Impact level projects and 2 representatives from Growth and At-Large stages.

If you'd like more info/context on the governance of the OpenJS Foundation, please let me know or follow this repo. The main point I hope you take away is that the foundation is to be run by and for the projects, and to do that we need participants from the project community.

## Request
As a Growth stage project, architect is strongly encouraged to send representatives to participate in CPC meetings, to advise on programs and support that will be helpful to it, and to nominate someone from the project community to serve in a voting capacity. 

We anticipate having our first 'official' CPC meeting on May 30 or 31 at the Collaborator Summit in Berlin (sidebar, you should come!). In the interim, we would love for architect project members to participate in the Bootstrap CPC meetings which are currently held on Mondays (watch [this repo](https://github.com/openjs-foundation/bootstrap/issues/150) for meeting details).

If this is not the correct forum to raise this, please let me know and I will close the issue and post it in the preferred channel. Note that I'm posting essentially the same message to all OpenJS Foundation project repos, because I want to get the word out and make sure we all have the same information. 

your pal,
Jory

**Comment by ryanblock** [comment]
Hi Jory! Nice to hear from you again. 🌈

Thanks for posting this here, it's super helpful.

As creator and chief steward of the project, I'd like to nominate @brianleroux to serve as Architect's representative to OpenJS.

Looking forward to the Summit!

**Comment by jorydotcom** [comment]
> As creator and chief steward of the project, I'd like to nominate @brianleroux to serve as Architect's representative to OpenJS.

I call this being 'volun-told' :joy: ❤️ 

> Looking forward to the Summit!

Same!!!

**Comment by kborchers** [comment]
I also reached out directly to @brianleroux this morning to see if I could lend my services in this capacity but haven't heard back yet. Having been involved in the project from very early, helping launch it as a JSF project, and having built many demos and promoted it extensively while I was the JSF exec director, I am still very passionate about the success of this project and would be happy to help in this way as my ability to contribute from a technical/code standpoint is just non-existent at this time.

Happy to help if the team thinks that is the best option for the project. 🙂

**Comment by ryanblock** [comment]
@jorydotcom I knowwwwww, you should have seen the look on his face when he read that email. Priceless!

@kborchers much obliged Kris, as always you are terribly kind and generous! 🌈

**Comment by brianleroux** [comment]
sorry for the delay! startups. and a very good example of why I really appreciate the offer and would like to put the nomination to @kborchers! 💕 he's been here since the very beginning and super aligned on issues of open source governance. I'll still def be active in the foundation and will strive to hit the meetings as much as possible. (in addition to the usual creating and/or fixing bugs! 😝 )

**Comment by ryanblock** [comment]
Not sure if we're following Robert's Rules here, but seconded!

**Comment by kborchers** [comment]
Thanks all! Assuming there is no one else interested in being the Architect nominee for election to the CPC, I'll go ahead and comment on that issue, referencing this one. ❤️
