### ISSUE TITLE
Support for binary request body

### ISSUE THREAD

**Issue by mikeal** [arc-repos/architect#353]
Binary uploads don’t appear to be working.

I’m doing a simple PUT request with a binary body and a Content-Type of `application/octet-stream` and I’m getting a 400 error from CloudFront.

```
{"message": "Could not parse request body into json: Unrecognized token \'YWRzZg\': was expecting (\'true\', \'false\' or \'null\')\n at [Source: (byte[])\"YWRzZg==\"; line: 1, column: 8]"}
```

Poking through the code base it looks like there has been some attempt at supporting binary when invoking http functions https://github.com/arc-repos/architect/blob/de850cea900a8180377613ccc5599970c3063b06/src/sandbox/http/invoke-http.js but it looks like the CloudFront config is set to JSON ☹️

**Comment by ryanblock** [comment]
JSON isn’t necessarily the problem, but happy to take a look at this, been spending a lot of time in that part of the codebase lately. Can you provide me with some example example client and server code that should be working?

**Comment by mikeal** [comment]
Here’s my test using w/ the sandbox.

```javascript
const arc = require('@architect/architect')
const data = require('@architect/data')
const bent = require('bent')
const { test } = require('tap')

const headers = { 'content-type': 'application/octet-stream' }
const put = bent('PUT', 201, 'buffer', headers)

let token = Math.random().toString()

test('get /', async t => {
  let close = await arc.sandbox.start()
  await data.tokens.put({token, user: 'mikeal'})
  let url = `http://localhost:3333/block?token=${token}`
  let result = await put(url, Buffer.from('adsf'))
  await close()
  console.log(result.toString())
})
```

And here’s a script that hits a live lambda.

```javascript
const bent = require('bent')

const lambdaHost = `some-randomness.execute-api.us-west-2.amazonaws.com`
const baseurl = `https://${lambdaHost}/staging`
const headers = { 'content-type': 'application/octet-stream' }
const put = bent('PUT', 201, 'buffer', headers)

const run = async t => {
  let url = `${baseurl}/block?token=${process.env.TESTTOKEN}`
  let result = await put(url, Buffer.from('adsf'))
  console.log(result.toString())
}
run()
```

The lambda is basically just the default arc lambda modified to give me some information about the body since that’s what I’m testing, and to return a `201` response.

```javascript
const data = require('@architect/data')

exports.handler = async function http(req) {
  console.error(req)
  let token = await data.tokens.get(req.query)

  return {
    status: 201,
    headers: {'content-type': 'text/html; charset=utf8'},
    body: '<h1>'+ JSON.stringify(req) +'</h1>'
  }
}
```

And it’s just a very simple .arc file.

```
@app
ipld-earth

@http
get /
put /block

@tables
tokens
  token *String
```

You could strip out all the token stuff for testing purposes.

**Comment by ryanblock** [comment]
Sweet, thanks, I'll take this for a spin. Since this gets into API Gateway's VTL template stuff, which is a real challenge, may take me a minute. But this use case is exactly what I'd like to ensure we support, please stand by!

**Comment by mikeal** [comment]
Awesome, let me know how it goes :)

**Comment by ryanblock** [comment]
So far so good, thinking over options. We have a limited toolset available to resolve.

If we said "as a rule, all arc `application/binary-octet` bodies come base64 encoded" would that be super gross to you?

**Comment by mikeal** [comment]
base64 is what I’m trying to avoid, it can be rather expensive. if base encoding worked well enough i’d be fine with json and i’d just encode the string as json. in fact, i’d say that if the only option is base64 it’s best to just not support it at all and leave it with only json, it would be simpler and more consistent.

**Comment by ryanblock** [comment]
Ok, in that case, first pass findings don't look so good. API Gateway has this pretty absurdly complicated means of passing binary data in and out of the system, with a pretty limited tool set, all of which depends on base64 transformations under the hood. The templating logic related to base64 encoding is at the heart of all binary handling in APIG.

One thing we could potentially do is deal with the base64 encoding/decoding in Arc Functions land so you just potentially receive a buffer. But if your concern is that dealing with base encoding is going to be too computationally expensive, that would only move the expensive operations from your code to a dependency.

Let me know what you think about that though, and I'll keep noodling on this!

**Comment by mikeal** [comment]
Hrm... on second thought, I would save an encoding on the client at the very least. 

I was sort of forgetting that my expectation in arc was to receive a Buffer when uploading `application/octet-stream`, so meeting those expectations is probably a better developer experience in general.

Also, I now wonder if the request body limit in lambda is the size of the binary or the base64 string which is roughly 33% larger.

**Comment by ryanblock** [comment]
Re-reading this thread, just wanted to clarify that we're talking about the same stuff, as I may have misinterpreted (or not clearly communicated) some things.

What I'm proposing is that client does its normal binary `application/octet-stream` put, and isn't responsible for any encoding. Then, further down the chain, your code in Lambda receives the body as base64 encoded. (Maybe that was clear, idk, but I re-read this thread and thought it may have sounded like I was suggesting the client is responsible for base encoding – it's not, that's all happening inside API Gateway. But the server(less)-side code is responsible for base → Buffer.)

Request limit question is def one worth testing, will have to look into that!

**Comment by mikeal** [comment]
It would be nicer to get a Buffer in the lambda function but even with
base64 I can make do.

**Comment by ryanblock** [comment]
I am hopeful I can deliver a base payload, but it's pretty unlikely I can deliver a Buffer (but I'll keep looking).

**Comment by mikeal** [comment]
If you can't send a Buffer, it would be best to use some kind of envelope
so that you can distinguish between sending a JSON string and binary.
Something like `{ base64: "encodedString" }`.

**Comment by ryanblock** [comment]
Yeah, that was my plan, tentatively.

**Comment by ryanblock** [comment]
Branch here: https://github.com/arc-repos/architect/pull/360

Reqs with `application/octet-stream` and `multipart/form-data` will appear in the req object as `body: { base64: 'encodedString' }`

Could use some assistance on `multipart/form-data` verification.

Still working on the `sandbox` impl!

**Comment by ryanblock** [comment]
Just pushed the `sandbox` impl. This should be ready to go – any final feedback before I merge?

**Comment by ryanblock** [comment]
Merged to master, will be released in the next day or two as `5.6.4`!

**Comment by mikeal** [comment]
The sandbox seems to work fine but I’m still getting the same error on staging after re-deploying. Is there anything i need to re-run in order to get the deployment environment updated?

**Comment by ryanblock** [comment]
Deploys only update Lambdas and static assets, they skip over lower level infra / settings, such as API Gateway in this case. I have it in my backlog to whip up `npx inventory --upgrade` to actually upgrade existing infra, but I haven't gotten to that yet.

One option is to jump in there and swap out the templates by hand. Another is to provision up a fresh API and use that. (That could be a bit annoying, as you'll have to rename all your package files' name fields, but it's otherwise pretty straightforward.)

I could also toss up a gist of the script I use to upgrade our live API Gateway infra at Begin, let me know if that'd be helpful!

**Comment by mikeal** [comment]
The gist would be quite helpful while we don’t have the upgrade option implemented :)

**Comment by ryanblock** [comment]
Ok, here you go! https://gist.github.com/ryanblock/205c57fff6c8b0fb4e9bbfdf9cb62761 I make no claims that it won't break all your things. 😅

Please note: I have not run this with the new binary templates from 5.7, so L146 may or may not throw errors on the upsert I'm attempting there – AWS is inconsistent and even contextual about some behavior, even within a single method. Anyway, if it gives you trouble, try swapping `replace` with `add`.

**Comment by mikeal** [comment]
since there aren’t any notifications for gist comments I figured I should alert you to the issue i saw with the script here :) https://gist.github.com/ryanblock/205c57fff6c8b0fb4e9bbfdf9cb62761#gistcomment-2893122

**Comment by mikeal** [comment]
Sorry, just saw your comment here about swapping out replace for add, that fixed it ;)

**Comment by ryanblock** [comment]
@mikeal apologies, in that gist I think I copy/pasted over the `x-www-form-urlencoded` template – I updated that gist, you may want to run it again!

**Comment by mikeal** [comment]
re-run, thanks :)

-Mikeal
________________________________
